#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/gps/gps-plugin.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/map/agent1-map.n3 --query https://github.com/josd/eye/blob/master/reasoning/map/agent1-query.n3 > agent1-proof.n3
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/gps/gps-plugin.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/map/agent2-map.n3 --proof https://github.com/josd/eye/blob/master/reasoning/map/agent1-proof.n3 --query https://github.com/josd/eye/blob/master/reasoning/map/agent2-query.n3 > agent2-proof.n3
