#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/map . --nope http://josd.github.io/eye/reasoning/map/gps-plugin.n3 http://josd.github.io/eye/reasoning/map/agent1-map.n3 --query http://josd.github.io/eye/reasoning/map/agent1-query.n3 > agent1-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning/map . http://josd.github.io/eye/reasoning/map/gps-plugin.n3 http://josd.github.io/eye/reasoning/map/agent1-map.n3 --query http://josd.github.io/eye/reasoning/map/agent1-query.n3 > agent1-proof.n3

eye "$@" --wcache http://josd.github.io/eye/reasoning/map . --nope http://josd.github.io/eye/reasoning/map/gps-plugin.n3 http://josd.github.io/eye/reasoning/map/agent2-map.n3 --proof http://josd.github.io/eye/reasoning/map/agent1-proof.n3 --query http://josd.github.io/eye/reasoning/map/agent2-query.n3 > agent2-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning/map . http://josd.github.io/eye/reasoning/map/gps-plugin.n3 http://josd.github.io/eye/reasoning/map/agent2-map.n3 --proof http://josd.github.io/eye/reasoning/map/agent1-proof.n3 --query http://josd.github.io/eye/reasoning/map/agent2-query.n3 > agent2-proof.n3
