#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/witch/witch.n3 --query http://eyereasoner.github.io/eye/reasoning/witch/witch-goal.n3 --output witch-proof.n3
