#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example1.n3 --pass-only-new > example1-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example2.n3 --pass-only-new > example2-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example3.n3 --pass-only-new > example3-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example4.n3 --pass-only-new > example4-pass-only-new.n3
