#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example1.n3 --pass > example1-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example2.n3 --pass > example2-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example3.n3 --pass > example3-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example4.n3 --pass > example4-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/nps/example5.n3 --pass > example5-pass.n3
