#!/bin/bash
eye "$@" --nope https://raw.githubusercontent.com/josd/eye/master/reasoning/bi/biP.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/bi/biQ.n3 > biA.n3
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/bi/biP.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/bi/biQ.n3 > biE.n3
eye "$@" --nope https://raw.githubusercontent.com/josd/eye/master/reasoning/bi/math_flowc.n3 --pass > math_flowc_answer.n3
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/bi/math_flowc.n3 --pass > math_flowc_proof.n3

