#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/bi . --nope http://josd.github.io/eye/reasoning/bi/biP.n3 --query http://josd.github.io/eye/reasoning/bi/biQ.n3 > biA.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning/bi . http://josd.github.io/eye/reasoning/bi/biP.n3 --query http://josd.github.io/eye/reasoning/bi/biQ.n3 > biE.n3

