#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/bi/biP.n3 --query http://eyereasoner.github.io/eye/reasoning/bi/biQ.n3 --output biA.n3
