#!/bin/bash
function test {
    python3 brain.py http://josd.github.io/eye/brain/bell.n3
    python3 brain.py http://josd.github.io/eye/brain/easter.n3
    python3 brain.py http://josd.github.io/eye/brain/einstein.n3
    python3 brain.py http://josd.github.io/eye/brain/euler.n3
    python3 brain.py http://josd.github.io/eye/brain/fibonacci.n3
    python3 brain.py http://josd.github.io/eye/brain/graph.n3
    python3 brain.py http://josd.github.io/eye/brain/grapht.n3
    python3 brain.py http://josd.github.io/eye/brain/grover.n3
    python3 brain.py http://josd.github.io/eye/brain/list.n3
    python3 brain.py http://josd.github.io/eye/brain/socrates.n3
    python3 brain.py http://josd.github.io/eye/brain/tree.n3
    python3 brain.py http://josd.github.io/eye/brain/xanthippe.n3
    python3 brain.py http://www.agfa.com/w3c/euler/example003P.n3
    python3 brain.py http://www.agfa.com/w3c/euler/medI.n3
}

test "$@" |& tee test.txt
for f in *.py; do python3 "$f" | tee -a test.txt; done
