#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/socrates/socrates.n3 --query http://eyereasoner.github.io/eye/reasoning/socrates/socrates-query.n3 --output socrates-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/socrates/socrates.n3 --query http://eyereasoner.github.io/eye/reasoning/socrates/socrates-query.n3 --output socrates-proof.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --proof http://eyereasoner.github.io/eye/reasoning/socrates/socrates-proof.n3 --pass-only-new --output socrates-lemma.n3
