#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/nexus .. --nope https://eyereasoner.github.io/eye/nexus/packaging/packaging.trig --sparql-query https://eyereasoner.github.io/eye/nexus/packaging/packaging-query.rq --rdf-trig-output --output packaging-answer.trig
