#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/pptbank/bankSW.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/pptbank/checking.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/pptbank/query.n3 > proof.n3
