#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/pptbank/bankSW.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/pptbank/checking.n3 --query https://github.com/josd/eye/blob/master/reasoning/pptbank/query.n3 > proof.n3
