#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/mmln/mmln-gv-example.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/mmln/mmln-gv-mln.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/mmln/mmln-plugin.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/mmln/mmln-gv-query.n3 > mmln-gv-proof.n3
