#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/mmln/mmln-gv-example.n3 http://eyereasoner.github.io/eye/reasoning/mmln/mmln-gv-mln.n3 http://eyereasoner.github.io/eye/reasoning/mmln/mmln-plugin.n3 --query http://eyereasoner.github.io/eye/reasoning/mmln/mmln-gv-query.n3 --output mmln-gv-proof.n3
