#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/mmln/mmln-gv-example.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/mmln/mmln-gv-mln.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/mmln/mmln-plugin.n3 --query https://github.com/josd/eye/blob/master/reasoning/mmln/mmln-gv-query.n3 > mmln-gv-proof.n3
