PREFIX math: <http://www.w3.org/2000/10/swap/math#>
PREFIX : <https://eyereasoner.github.io/eye/reasoning#>

CONSTRUCT {
    (?X ?A ?B) :fib ?Y.
}

WHERE {
    ?X math:greaterThan 1.
    (?X 1) math:difference ?C.
    (?A ?B) math:sum ?D.
    (?C ?B ?D) :fib ?Y.
}
