PREFIX : <https://eyereasoner.github.io/eye/reasoning#>

CONSTRUCT {
    (0) :fibonacci ?F0.
    (1) :fibonacci ?F1.
    (6) :fibonacci ?F6.
    (91) :fibonacci ?F91.
    (283) :fibonacci ?F283.
    (3674) :fibonacci ?F3674.
}

WHERE {
    (0) :fibonacci ?F0.
    (1) :fibonacci ?F1.
    (6) :fibonacci ?F6.
    (91) :fibonacci ?F91.
    (283) :fibonacci ?F283.
    (3674) :fibonacci ?F3674.
}
