#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/deep-taxonomy/test-dl.ttl --query https://eyereasoner.github.io/eye/reasoning/deep-taxonomy/parteval-subclass.n3 --output test-dt.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. https://eyereasoner.github.io/eye/reasoning/deep-taxonomy/test-dt.n3 --image dtpe.pvm
