#!/bin/bash
swipl -x dtpe.pvm -- --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/deep-taxonomy/test-facts.ttl --query https://eyereasoner.github.io/eye/reasoning/deep-taxonomy/test-query.n3 --output test-answer.ttl
