#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/matrix/matrix.n3 --query http://josd.github.io/eye/reasoning/matrix/matrix_query.n3 --output matrix_answer.n3
