#!/bin/bash
eye "$@" --nope https://raw.githubusercontent.com/josd/eye/master/reasoning/equation4/polynomial.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/equation4/query.n3 > result.n3
