#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/meta-interpretation-test/meta-interpretation.pl3 --output meta-interpretation-output.pl3
