#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --quiet --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/dt/test-dl.ttl --query http://eyereasoner.github.io/eye/reasoning/dt/parteval-subclass.n3 --output test-dt.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --quiet --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/dt/test-dt.n3 --image dtpe.pvm
