#!/bin/bash
eye "$@" --quiet --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/dt/test-dl.n3 --query http://eyereasoner.github.io/eye/reasoning/dt/parteval-subclass.n3 --output test-dt.n3
eye "$@" --quiet --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/dt/test-dt.n3 --image dtpe.pvm
