#!/bin/bash
eye "$@" --quiet --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/dt/test-dl.n3 --query http://josd.github.io/eye/reasoning/dt/parteval-subclass.n3 > test-dt.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/dt/test-dt.n3 --image dtpe.pvm
