#!/bin/bash -x
swipl -x dtpe.pvm -- "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/dt/test-facts.n3 --query http://eyereasoner.github.io/eye/reasoning/dt/test-query.n3 --output test-answer.n3
