#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/dt/test-facts.n3 http://josd.github.io/eye/reasoning/dt/test-dt-10000.n3 --query http://josd.github.io/eye/reasoning/dt/test-query.n3 > test-proof-10000.n3
