#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/dt/test-facts.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/dt/test-dt-1000.n3 --query https://github.com/josd/eye/blob/master/reasoning/dt/test-query.n3 > test-proof-1000.n3
