#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --turtle http://josd.github.io/eye/reasoning/lubm/facts.n3 http://josd.github.io/eye/reasoning/lubm/rules.n3 --query http://josd.github.io/eye/reasoning/lubm/query.n3 --output answer.n3
