#!/bin/bash
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --turtle http://eyereasoner.github.io/eye/reasoning/lubm/facts.n3 http://eyereasoner.github.io/eye/reasoning/lubm/rules.n3 --query http://eyereasoner.github.io/eye/reasoning/lubm/query.n3 --output answer.n3
