#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/path-discovery/path-discovery-algorithm.n3 --turtle https://eyereasoner.github.io/eye/reasoning/path-discovery/path-discovery-data.ttl --output path-discovery-answer.n3
