# inference fuse

PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX : <https://eyereasoner.github.io/ns#>

CONSTRUCT {
    (?X) log:allPossibleCases ().
} WHERE {
    ?X :color :black.
    ?X :color :white.
}
