#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let .. --nope https://eyereasoner.github.io/eye/let/fuse/fuse.ttl --sparql-fuse https://eyereasoner.github.io/eye/let/fuse/fuse.rq 2> fuse-output.err
