#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/proof-by-contrapositive-test/proof-by-contrapositive.pl3 --output proof-by-contrapositive-output.pl3
