#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope --turtle https://eyereasoner.github.io/eye/color/lubm/facts.ttl https://eyereasoner.github.io/eye/color/lubm/rules.n3 --query https://eyereasoner.github.io/eye/color/lubm/query.n3 --output answer.n3
