#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/cha58/cha58-data.n3 --blogic http://josd.github.io/eye/reasoning/cha58/cha58-blogic.n3 --output cha58-answer.n3
