#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/cha58/cha58-data.ttl --blogic http://eyereasoner.github.io/eye/reasoning/cha58/cha58-blogic.n3s --output cha58-answer.ttl
