#!/bin/bash -x
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/cha58/cha58-data.ttl http://josd.github.io/eye/reasoning/cha58/cha58-rules.n3 --query  http://josd.github.io/eye/reasoning/cha58/cha58-query.n3 > cha58-answer.ttl
