#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --rdf-trig-output https://eyereasoner.github.io/eye/reasoning/n3plus1/in.n3 --query https://eyereasoner.github.io/eye/reasoning/n3plus1/query.n3 --output out.n3
