#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/wolf-goat-cabbage-test/wolf-goat-cabbage.pl3 --output wolf-goat-cabbage-output.pl3
