#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/eyelet .. --nope --turtle https://eyereasoner.github.io/eye/eyelet/path-discovery/path-discovery-data.ttl https://eyereasoner.github.io/eye/eyelet/path-discovery/path-discovery.ttl --output path-discovery-answer.ttl
