#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --turtle https://eyereasoner.github.io/eye/reasoning/workplace-test/workplace-data.ttl --pl3 https://eyereasoner.github.io/eye/reasoning/workplace-test/workplace.pl3 --output workplace-output.pl3
