#!/bin/bash
for f in *.n3
do
    if [ "$f" != "clr.n3" ]; then
        echo + eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --nope $f clr.n3 --output answer/$f
        eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --nope $f clr.n3 --output answer/$f
        echo + eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 $f clr.n3 --output proof/$f
        eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 $f clr.n3 --output proof/$f
    fi
done
