#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/reif/data.n3 http://josd.github.io/eye/reasoning/reif/reify.n3 --pass --output data-reif.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/reif/data-reif.n3 http://josd.github.io/eye/reasoning/reif/dereify.n3 --pass --output data-roundtrip.n3
