#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --n3 https://eyereasoner.github.io/eye/reasoning/iq/iq.n3 --pass-all --output iq-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --n3 https://eyereasoner.github.io/eye/reasoning/iq/iq-extra.n3 --pass-all --output iq-extra-answer.n3
