#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://josd.github.io/eye/color .. --nope http://josd.github.io/eye/color/cha58/cha58-data.ttl http://josd.github.io/eye/color/cha58/cha58-rules.n3 --query  http://josd.github.io/eye/color/cha58/cha58-query.n3 --output cha58-answer.ttl
