#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
FAILED=0

echo -e "${YELLOW}------------------------${NORMAL}"
echo -e "${YELLOW}Running lingua/temp/test${NORMAL}"
echo -e "${YELLOW}------------------------${NORMAL}"
echo ""

echo -e "${YELLOW}testing with --trig input${NORMAL}"
pushd .. > /dev/null
for file in *.trig
do
    echo -en "$file "
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --nope --trig $file --output temp/answer/$file 2> /dev/null
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --trig $file --output temp/proof/$file 2> /dev/null
    if [[ $(git diff temp/*/$file | wc -l) -eq 0 ]]; then
        echo -e "${GREEN}OK${NORMAL}"
        ((OK++))
    else
        echo -e "${RED}FAILED${NORMAL}"
        ((FAILED++))
    fi
done
popd > /dev/null
echo ""

echo -e "${YELLOW}calculating ackermann(4, 2)${NORMAL}"
echo -en "ackermann42.trig "
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --nope ackermann42.trig --output answer/ackermann42.trig 2> /dev/null
if [[ $(git diff */ackermann42.trig | wc -l) -eq 0 ]]; then
    echo -e "${GREEN}OK${NORMAL}"
    ((OK++))
else
    echo -e "${RED}FAILED${NORMAL}"
    ((FAILED++))
fi
echo ""

echo -e "${YELLOW}Tests:${NORMAL} ${GREEN}${OK} OK${NORMAL} ${RED}${FAILED} FAILED${NORMAL}"
if [[ ${FAILED} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
