#!/bin/bash -x
eye --quiet append.ttl --output out/append.ttl
eye --quiet backward.ttl --output out/backward.ttl
eye --quiet forward.ttl --output out/forward.ttl
eye --quiet gen.ttl --output out/gen.ttl
eye --quiet notequal.ttl --output out/notequal.ttl
eye --quiet sha512.ttl --output out/sha512.ttl
eye --quiet fuse.ttl --output out/fuse.ttl 2> out/fuse.ttl.txt
eye --quiet union.ttl --output out/union.ttl
