#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/dcg/dcg.n3 --pass --output dcg-pass.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/dcg/dcg2.n3 --pass --output dcg2-pass.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/dcg/dcg3.n3 --pass --output dcg3-pass.n3
