#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/dcg/dcg.n3 --pass --output dcg-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/dcg/dcg2.n3 --pass --output dcg2-pass.n3
