#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/glass/test.n3 --query http://eyereasoner.github.io/eye/reasoning/glass/testQ.n3 --output testA.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/glass/test.n3 --query http://eyereasoner.github.io/eye/reasoning/glass/testQ.n3 --output testE.n3
