#!/bin/bash
#cwm http://josd.github.io/eye/reasoning/glass/test.n3 --think --filter=http://josd.github.io/eye/reasoning/glass/testQ.n3 > testC.n3
#cwm http://josd.github.io/eye/reasoning/glass/test.n3 --think --filter=http://josd.github.io/eye/reasoning/glass/testQ.n3 --why > testW.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/glass/test.n3 --query http://josd.github.io/eye/reasoning/glass/testQ.n3 > testA.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/glass/test.n3 --query http://josd.github.io/eye/reasoning/glass/testQ.n3 > testE.n3
