#!/bin/bash
#cwm https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/test.n3 --think --filter=https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/testQ.n3 > testC.n3
#cwm https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/test.n3 --think --filter=https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/testQ.n3 --why > testW.n3
eye "$@" --nope https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/test.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/testQ.n3 > testA.n3
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/test.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/glass/testQ.n3 > testE.n3
