#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --tactic limited-answer 1 https://eyereasoner.github.io/eye/color/rs/randomsample-rule.n3 --query https://eyereasoner.github.io/eye/color/rs/randomsample-query.n3 --output randomsample-proof.n3
