#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/issue25/test1.n3 --pass-only-new > test1-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/issue25/test2.n3 --pass-only-new > test2-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/issue25/test3.n3 --pass-only-new > test3-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/issue25/test4.n3 --pass-only-new > test4-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/issue25/test5.n3 --pass-only-new > test5-pass-only-new.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/issue25/test6.n3 --pass-only-new > test6-pass-only-new.n3
