#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/tak/tak.n3 --query http://eyereasoner.github.io/eye/reasoning/tak/takQ.n3 --output takA.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/tak/tak.n3 --query http://eyereasoner.github.io/eye/reasoning/tak/takQ.n3 --output takE.n3
