#!/bin/bash
eye "$@" --tactic limited-answer 1 https://raw.githubusercontent.com/josd/eye/master/reasoning/tak/tak.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/tak/takQ.n3 > takE.n3
