#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --tactic limited-answer 1 http://josd.github.io/eye/reasoning/tak/tak.n3 --query http://josd.github.io/eye/reasoning/tak/takQ.n3 --output takE.n3
