#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/graph/graph.axiom.n3 https://eyereasoner.github.io/eye/color/graph/rpo-rules.n3 --query https://eyereasoner.github.io/eye/color/graph/graph.filter.n3 --output graph.proof.n3
