#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/argus .. --nope https://eyereasoner.github.io/eye/argus/beetle12/beetle12.ttl --output beetle12-answer.ttl
