:- op(1200, xfx, :+).

answer(('<https://eyereasoner.github.io/ns#re>'(b, sk_0), '<https://eyereasoner.github.io/ns#re>'(c, sk_0))).

% proof steps
step(('<https://eyereasoner.github.io/ns#re>'(a, b), '<https://eyereasoner.github.io/ns#re>'(a, c):+true), true, ('<https://eyereasoner.github.io/ns#re>'(a, b), '<https://eyereasoner.github.io/ns#re>'(a, c))).
step(('<https://eyereasoner.github.io/ns#re>'(a, b), '<https://eyereasoner.github.io/ns#re>'(a, c):+true), true, ('<https://eyereasoner.github.io/ns#re>'(a, b), '<https://eyereasoner.github.io/ns#re>'(a, c))).
step(('<https://eyereasoner.github.io/ns#e>'(A, A):+'<https://eyereasoner.github.io/ns#re>'(A, _)), '<https://eyereasoner.github.io/ns#re>'(a, b), '<https://eyereasoner.github.io/ns#e>'(a, a)).
step(('<https://eyereasoner.github.io/ns#e>'(A, A):+'<https://eyereasoner.github.io/ns#re>'(_, A)), '<https://eyereasoner.github.io/ns#re>'(a, b), '<https://eyereasoner.github.io/ns#e>'(b, b)).
step(('<https://eyereasoner.github.io/ns#e>'(A, A):+'<https://eyereasoner.github.io/ns#re>'(_, A)), '<https://eyereasoner.github.io/ns#re>'(a, c), '<https://eyereasoner.github.io/ns#e>'(c, c)).
step(('<https://eyereasoner.github.io/ns#re>'(A, B):+'<https://eyereasoner.github.io/ns#e>'(A, B)), '<https://eyereasoner.github.io/ns#e>'(a, a), '<https://eyereasoner.github.io/ns#re>'(a, a)).
step(('<https://eyereasoner.github.io/ns#re>'(A, B):+'<https://eyereasoner.github.io/ns#e>'(A, B)), '<https://eyereasoner.github.io/ns#e>'(b, b), '<https://eyereasoner.github.io/ns#re>'(b, b)).
step(('<https://eyereasoner.github.io/ns#re>'(A, B):+'<https://eyereasoner.github.io/ns#e>'(A, B)), '<https://eyereasoner.github.io/ns#e>'(c, c), '<https://eyereasoner.github.io/ns#re>'(c, c)).
step(('<https://eyereasoner.github.io/ns#not_re>'(c, A):+'<https://eyereasoner.github.io/ns#re>'(b, A)), '<https://eyereasoner.github.io/ns#re>'(b, b), '<https://eyereasoner.github.io/ns#not_re>'(c, b)).
step(('<https://eyereasoner.github.io/ns#not_re>'(b, A):+'<https://eyereasoner.github.io/ns#re>'(c, A)), '<https://eyereasoner.github.io/ns#re>'(c, c), '<https://eyereasoner.github.io/ns#not_re>'(b, c)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_re>'(A, C), '<https://eyereasoner.github.io/ns#re>'(B, C)), ('<https://eyereasoner.github.io/ns#not_re>'(c, b), '<https://eyereasoner.github.io/ns#re>'(a, b)), '<https://eyereasoner.github.io/ns#not_e>'(c, a)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_re>'(A, C), '<https://eyereasoner.github.io/ns#re>'(B, C)), ('<https://eyereasoner.github.io/ns#not_re>'(c, b), '<https://eyereasoner.github.io/ns#re>'(b, b)), '<https://eyereasoner.github.io/ns#not_e>'(c, b)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_re>'(A, C), '<https://eyereasoner.github.io/ns#re>'(B, C)), ('<https://eyereasoner.github.io/ns#not_re>'(b, c), '<https://eyereasoner.github.io/ns#re>'(a, c)), '<https://eyereasoner.github.io/ns#not_e>'(b, a)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_re>'(A, C), '<https://eyereasoner.github.io/ns#re>'(B, C)), ('<https://eyereasoner.github.io/ns#not_re>'(b, c), '<https://eyereasoner.github.io/ns#re>'(c, c)), '<https://eyereasoner.github.io/ns#not_e>'(b, c)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_e>'(B, A)), '<https://eyereasoner.github.io/ns#not_e>'(c, a), '<https://eyereasoner.github.io/ns#not_e>'(a, c)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_e>'(B, A)), '<https://eyereasoner.github.io/ns#not_e>'(b, a), '<https://eyereasoner.github.io/ns#not_e>'(a, b)).
step(('<https://eyereasoner.github.io/ns#r>'(A, B):+'<https://eyereasoner.github.io/ns#re>'(A, B), '<https://eyereasoner.github.io/ns#not_e>'(A, B)), ('<https://eyereasoner.github.io/ns#re>'(a, b), '<https://eyereasoner.github.io/ns#not_e>'(a, b)), '<https://eyereasoner.github.io/ns#r>'(a, b)).
step(('<https://eyereasoner.github.io/ns#r>'(A, B):+'<https://eyereasoner.github.io/ns#re>'(A, B), '<https://eyereasoner.github.io/ns#not_e>'(A, B)), ('<https://eyereasoner.github.io/ns#re>'(a, c), '<https://eyereasoner.github.io/ns#not_e>'(a, c)), '<https://eyereasoner.github.io/ns#r>'(a, c)).
step(('<https://eyereasoner.github.io/ns#r>'(A, B), '<https://eyereasoner.github.io/ns#r>'(C, B):+'<https://eyereasoner.github.io/ns#r>'(D, A), '<https://eyereasoner.github.io/ns#r>'(D, C)), ('<https://eyereasoner.github.io/ns#r>'(a, b), '<https://eyereasoner.github.io/ns#r>'(a, b)), ('<https://eyereasoner.github.io/ns#r>'(b, sk_0), '<https://eyereasoner.github.io/ns#r>'(b, sk_0))).
step(('<https://eyereasoner.github.io/ns#r>'(A, B), '<https://eyereasoner.github.io/ns#r>'(C, B):+'<https://eyereasoner.github.io/ns#r>'(D, A), '<https://eyereasoner.github.io/ns#r>'(D, C)), ('<https://eyereasoner.github.io/ns#r>'(a, b), '<https://eyereasoner.github.io/ns#r>'(a, b)), ('<https://eyereasoner.github.io/ns#r>'(b, sk_0), '<https://eyereasoner.github.io/ns#r>'(b, sk_0))).
step(('<https://eyereasoner.github.io/ns#r>'(A, B), '<https://eyereasoner.github.io/ns#r>'(C, B):+'<https://eyereasoner.github.io/ns#r>'(D, A), '<https://eyereasoner.github.io/ns#r>'(D, C)), ('<https://eyereasoner.github.io/ns#r>'(a, b), '<https://eyereasoner.github.io/ns#r>'(a, c)), ('<https://eyereasoner.github.io/ns#r>'(b, sk_0), '<https://eyereasoner.github.io/ns#r>'(c, sk_0))).
step(('<https://eyereasoner.github.io/ns#r>'(A, B), '<https://eyereasoner.github.io/ns#r>'(C, B):+'<https://eyereasoner.github.io/ns#r>'(D, A), '<https://eyereasoner.github.io/ns#r>'(D, C)), ('<https://eyereasoner.github.io/ns#r>'(a, b), '<https://eyereasoner.github.io/ns#r>'(a, c)), ('<https://eyereasoner.github.io/ns#r>'(b, sk_0), '<https://eyereasoner.github.io/ns#r>'(c, sk_0))).
step(('<https://eyereasoner.github.io/ns#re>'(A, B):+'<https://eyereasoner.github.io/ns#r>'(A, B)), '<https://eyereasoner.github.io/ns#r>'(b, sk_0), '<https://eyereasoner.github.io/ns#re>'(b, sk_0)).
step(('<https://eyereasoner.github.io/ns#re>'(A, B):+'<https://eyereasoner.github.io/ns#r>'(A, B)), '<https://eyereasoner.github.io/ns#r>'(c, sk_0), '<https://eyereasoner.github.io/ns#re>'(c, sk_0)).
step(('<https://eyereasoner.github.io/ns#r>'(A, B), '<https://eyereasoner.github.io/ns#r>'(C, B):+'<https://eyereasoner.github.io/ns#r>'(D, A), '<https://eyereasoner.github.io/ns#r>'(D, C)), ('<https://eyereasoner.github.io/ns#r>'(b, sk_0), '<https://eyereasoner.github.io/ns#r>'(b, sk_0)), ('<https://eyereasoner.github.io/ns#r>'(sk_0, sk_0), '<https://eyereasoner.github.io/ns#r>'(sk_0, sk_0))).
step(('<https://eyereasoner.github.io/ns#r>'(A, B), '<https://eyereasoner.github.io/ns#r>'(C, B):+'<https://eyereasoner.github.io/ns#r>'(D, A), '<https://eyereasoner.github.io/ns#r>'(D, C)), ('<https://eyereasoner.github.io/ns#r>'(b, sk_0), '<https://eyereasoner.github.io/ns#r>'(b, sk_0)), ('<https://eyereasoner.github.io/ns#r>'(sk_0, sk_0), '<https://eyereasoner.github.io/ns#r>'(sk_0, sk_0))).
step(('<https://eyereasoner.github.io/ns#not_re>'(c, A):+'<https://eyereasoner.github.io/ns#re>'(b, A)), '<https://eyereasoner.github.io/ns#re>'(b, sk_0), '<https://eyereasoner.github.io/ns#not_re>'(c, sk_0)).
step(('<https://eyereasoner.github.io/ns#not_re>'(b, A):+'<https://eyereasoner.github.io/ns#re>'(c, A)), '<https://eyereasoner.github.io/ns#re>'(c, sk_0), '<https://eyereasoner.github.io/ns#not_re>'(b, sk_0)).
step((true:+'<https://eyereasoner.github.io/ns#re>'(b, A), '<https://eyereasoner.github.io/ns#re>'(c, A)), ('<https://eyereasoner.github.io/ns#re>'(b, sk_0), '<https://eyereasoner.github.io/ns#re>'(c, sk_0)), true).
step(('<https://eyereasoner.github.io/ns#e>'(A, A):+'<https://eyereasoner.github.io/ns#re>'(_, A)), '<https://eyereasoner.github.io/ns#re>'(b, sk_0), '<https://eyereasoner.github.io/ns#e>'(sk_0, sk_0)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_re>'(A, C), '<https://eyereasoner.github.io/ns#re>'(B, C)), ('<https://eyereasoner.github.io/ns#not_re>'(c, sk_0), '<https://eyereasoner.github.io/ns#re>'(c, sk_0)), '<https://eyereasoner.github.io/ns#not_e>'(c, c)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_re>'(A, C), '<https://eyereasoner.github.io/ns#re>'(B, C)), ('<https://eyereasoner.github.io/ns#not_re>'(b, sk_0), '<https://eyereasoner.github.io/ns#re>'(b, sk_0)), '<https://eyereasoner.github.io/ns#not_e>'(b, b)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#e>'(C, A), '<https://eyereasoner.github.io/ns#not_re>'(C, B)), ('<https://eyereasoner.github.io/ns#e>'(b, b), '<https://eyereasoner.github.io/ns#not_re>'(b, sk_0)), '<https://eyereasoner.github.io/ns#not_e>'(b, sk_0)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#e>'(C, A), '<https://eyereasoner.github.io/ns#not_re>'(C, B)), ('<https://eyereasoner.github.io/ns#e>'(c, c), '<https://eyereasoner.github.io/ns#not_re>'(c, sk_0)), '<https://eyereasoner.github.io/ns#not_e>'(c, sk_0)).
step(('<https://eyereasoner.github.io/ns#re>'(A, B):+'<https://eyereasoner.github.io/ns#e>'(A, B)), '<https://eyereasoner.github.io/ns#e>'(sk_0, sk_0), '<https://eyereasoner.github.io/ns#re>'(sk_0, sk_0)).
step(('<https://eyereasoner.github.io/ns#r>'(A, B):+'<https://eyereasoner.github.io/ns#re>'(A, B), '<https://eyereasoner.github.io/ns#not_e>'(A, B)), ('<https://eyereasoner.github.io/ns#re>'(b, b), '<https://eyereasoner.github.io/ns#not_e>'(b, b)), '<https://eyereasoner.github.io/ns#r>'(b, b)).
step(('<https://eyereasoner.github.io/ns#r>'(A, B):+'<https://eyereasoner.github.io/ns#re>'(A, B), '<https://eyereasoner.github.io/ns#not_e>'(A, B)), ('<https://eyereasoner.github.io/ns#re>'(c, c), '<https://eyereasoner.github.io/ns#not_e>'(c, c)), '<https://eyereasoner.github.io/ns#r>'(c, c)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_e>'(B, A)), '<https://eyereasoner.github.io/ns#not_e>'(b, sk_0), '<https://eyereasoner.github.io/ns#not_e>'(sk_0, b)).
step(('<https://eyereasoner.github.io/ns#not_e>'(A, B):+'<https://eyereasoner.github.io/ns#not_e>'(B, A)), '<https://eyereasoner.github.io/ns#not_e>'(c, sk_0), '<https://eyereasoner.github.io/ns#not_e>'(sk_0, c)).
