#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/diamond-property-test/diamond-property.pl3 --output diamond-property-output.pl3
