#!/bin/bash
eye "$@" --nope  palindrome.n3 palindrome-declarations.n3  preduction-plugin.n3 --query palindrome-preduction.n3 > palindrome2.n3
eye "$@"  http://josd.github.io/eye/reasoning/preduction/palindrome.n3 --query http://josd.github.io/eye/reasoning/preduction/palindrome-query.n3 > palindrome-proof.n3
eye "$@"  http://josd.github.io/eye/reasoning/preduction/palindrome2.n3 --query http://josd.github.io/eye/reasoning/preduction/palindrome2-query.n3 > palindrome2-proof.n3
eye "$@" --nope  food.n3 food-declarations.n3  preduction-plugin.n3 --query food-preduction.n3 > food2.n3
eye "$@"  http://josd.github.io/eye/reasoning/preduction/food-example.n3  http://josd.github.io/eye/reasoning/preduction/food.n3  http://josd.github.io/eye/reasoning/rpo/rdfs-subClassOf.n3 --query http://josd.github.io/eye/reasoning/preduction/food-query.n3 > food-proof.n3
eye "$@"  http://josd.github.io/eye/reasoning/preduction/food-example.n3  http://josd.github.io/eye/reasoning/preduction/food2.n3 --query http://josd.github.io/eye/reasoning/preduction/food-query.n3 > food2-proof.n3
