#!/bin/bash
pushd reasoning > /dev/null
./test
popd > /dev/null
echo ""
pushd let-sparql > /dev/null
./test
popd > /dev/null
echo ""
pushd let-python > /dev/null
./test
popd > /dev/null
echo ""
pushd let-prolog > /dev/null
./test
popd > /dev/null
echo ""
pushd let-lean > /dev/null
./test
popd > /dev/null
