#!/bin/bash
pushd reasoning > /dev/null
./test
popd > /dev/null
echo ""
pushd let-blogic > /dev/null
./test
popd > /dev/null
echo ""
pushd let-lingua > /dev/null
./test
popd > /dev/null
echo ""
pushd let-turtle > /dev/null
./test
popd > /dev/null
echo ""
pushd let-sparql > /dev/null
./test
popd > /dev/null
echo ""
pushd let-prolog > /dev/null
./test
popd > /dev/null
echo ""
pushd let-python > /dev/null
./test
popd > /dev/null
echo ""
pushd let-nodejs > /dev/null
./test
popd > /dev/null
