#!/bin/bash
pushd reasoning > /dev/null
./test
popd > /dev/null
echo ""
pushd let-blogic > /dev/null
./test
popd > /dev/null
echo ""
pushd let-clogic > /dev/null
./test
popd > /dev/null
echo ""
pushd let-trig > /dev/null
./test
popd > /dev/null
echo ""
pushd let-turtle > /dev/null
./test
popd > /dev/null
echo ""
pushd let-sparql > /dev/null
./test
popd > /dev/null
echo ""
pushd let-prolog > /dev/null
./test
popd > /dev/null
echo ""
pushd let-python > /dev/null
./test
popd > /dev/null
echo ""
pushd let-nodejs > /dev/null
./test
popd > /dev/null
echo ""
pushd let-tsnode > /dev/null
./test
popd > /dev/null
echo ""
pushd let-rust > /dev/null
./test
popd > /dev/null
