#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/graph/graph.axiom.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/graph/rpo-rules.n3 --query https://github.com/josd/eye/blob/master/reasoning/graph/graph.filter.n3 > graph.proof.n3
