#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/graph/graph.axiom.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/graph/rpo-rules.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/graph/graph.filter.n3 > graph.proof.n3
