#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --quiet --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/dt/test-dl.ttl --query https://eyereasoner.github.io/eye/color/dt/parteval-subclass.n3 --output test-dt.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --quiet --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/dt/test-dt.n3 --image dtpe.pvm
