#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/rng/socrates.ttl https://eyereasoner.github.io/eye/reasoning/rng/rng.n3 --output socrates-answer.ttl
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/rng/age.ttl https://eyereasoner.github.io/eye/reasoning/rng/rng.n3 --output age-answer.ttl
