#!/bin/bash
eye "$@" --nope --prolog http://josd.github.io/eye/reasoning/lee/lee_program.pl --query http://josd.github.io/eye/reasoning/lee/lee_query.n3 > lee_answer.n3
eye "$@" --prolog http://josd.github.io/eye/reasoning/lee/lee_program.pl --query http://josd.github.io/eye/reasoning/lee/lee_query.n3 > lee_proof.n3
