#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/lee/lee.n3 --query http://eyereasoner.github.io/eye/reasoning/lee/leeQ.n3 --output leeA.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/lee/lee.n3 --query http://eyereasoner.github.io/eye/reasoning/lee/leeQ.n3 --output leeE.n3
