#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/swet/swetA.n3 http://josd.github.io/eye/reasoning/swet/swetD.n3 --query=http://josd.github.io/eye/reasoning/swet/swetQ01.n3 --output swetA01.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/swet/swetA.n3 http://josd.github.io/eye/reasoning/swet/swetD.n3 --query=http://josd.github.io/eye/reasoning/swet/swetQ11.n3 --output swetA11.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/swet/swetA.n3 http://josd.github.io/eye/reasoning/swet/swetD.n3 --query=http://josd.github.io/eye/reasoning/swet/swetQ21.n3 --output swetA21.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/swet/swetA.n3 http://josd.github.io/eye/reasoning/swet/swetD.n3 --query=http://josd.github.io/eye/reasoning/swet/swetQ31.n3 --output swetA31.n3
