#!/bin/bash
eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/swet/swetA.n3 https://github.com/josd/eye/blob/master/reasoning/swet/swetD.n3 --query=https://github.com/josd/eye/blob/master/reasoning/swet/swetQ01.n3 > swetA01.n3
eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/swet/swetA.n3 https://github.com/josd/eye/blob/master/reasoning/swet/swetD.n3 --query=https://github.com/josd/eye/blob/master/reasoning/swet/swetQ11.n3 > swetA11.n3
eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/swet/swetA.n3 https://github.com/josd/eye/blob/master/reasoning/swet/swetD.n3 --query=https://github.com/josd/eye/blob/master/reasoning/swet/swetQ21.n3 > swetA21.n3
eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/swet/swetA.n3 https://github.com/josd/eye/blob/master/reasoning/swet/swetD.n3 --query=https://github.com/josd/eye/blob/master/reasoning/swet/swetQ31.n3 > swetA31.n3

eye "$@" https://github.com/josd/eye/blob/master/reasoning/swet/swetA.n3 --query=https://github.com/josd/eye/blob/master/reasoning/swet/swetQ.n3 > swet_proof.n3
