#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --tactic limited-answer 1 http://eyereasoner.github.io/eye/reasoning/dp/dp.n3 --query http://eyereasoner.github.io/eye/reasoning/dp/dpQ.n3 --output dpE.n3
