#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/dp . --tactic limited-answer 1 http://josd.github.io/eye/reasoning/dp/dp.n3 --query http://josd.github.io/eye/reasoning/dp/dpQ.n3 > dpE.n3
