#!/bin/bash
# ------------
# EYE research
# ------------

pushd ~/github.com/josd/eye/research
echo -n > research.txt
echo "# $(date)" > research.diff
IMATCH="^diff|^index|^Binary|^--|^\+-|\+\+|^@@|#Processed by|#DONE|in=|#ENDS"

for dir in */
do
    pushd ${dir}
    ./test --no-genid |& tee -a ../research.txt
    git diff -U0 . | grep -E -v "$IMATCH" >> ../research.diff
    popd
done

eye  research.diff --pass > /dev/null
popd
