#!/bin/bash -x
eye --quiet --nope --legacy negation-predicates.ttl --output out/negation-predicates.ttl.out
eye --quiet --nope --legacy negation-predicates.jsonld.ttl --output out/negation-predicates.jsonld.ttl.out
