#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/socrates-star/socrates.n3 --query http://eyereasoner.github.io/eye/reasoning/qgen/qgen.n3 --output query.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/socrates-star/socrates.n3 --query http://eyereasoner.github.io/eye/reasoning/qgen/query.n3 --output answer.n3
