#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/tfcontext/data-001.n3 http://eyereasoner.github.io/eye/reasoning/tfcontext/rules-001.n3 --query http://eyereasoner.github.io/eye/reasoning/tfcontext/query-001.n3 --output proof-001.n3
