#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/tfcontext/data-001.n3 http://eyereasoner.github.io/eye/reasoning/tfcontext/rules-001.n3 --query http://eyereasoner.github.io/eye/reasoning/tfcontext/query-001.n3 --output proof-001.n3
