#!/bin/bash
eye "$@" --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/tfcontext/data-001.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/tfcontext/rules-001.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/tfcontext/query-001.n3 > proof-001.n3
