#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/evolutionary-algorithm-test/evolutionary-algorithm.pl3 --output evolutionary-algorithm-output.pl3
