#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/lldm/lldmD.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/lldm/lldmP.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/lldm/lldmF.n3 > lldmE.n3
