#!/bin/bash
eye "$@" https://github.com/josd/eye/blob/master/reasoning/lldm/lldmD.n3 https://github.com/josd/eye/blob/master/reasoning/lldm/lldmP.n3 --query https://github.com/josd/eye/blob/master/reasoning/lldm/lldmF.n3 > lldmE.n3
