PREFIX math: <http://www.w3.org/2000/10/swap/math#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX : <https://eyereasoner.github.io/ns#>

# proof by contradiction
CONSTRUCT {
    ?X a :Positive.
} WHERE {
    5 log:repeat ?X.
    {
        CONSTRUCT {
            ?X a :Positive.
        } WHERE {
            ?X math:notLessThan 0.
        }
        CONSTRUCT {
            (?X) log:allPossibleCases ().
        } WHERE {
            ?X a :Positive.
        }
    } log:satisfiable false.
}
