PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX : <https://eyereasoner.github.io/ns#>

# facts
CONSTRUCT {
    :Socrates a :Human.
} WHERE {}

# proof by contradiction
CONSTRUCT {
    ?X a :Mortal.
} WHERE {
    ?X a :Human.
    {
        ?X a :Human.
        CONSTRUCT {
            ?X a :Mortal.
        } WHERE {
            ?X a :Human.
        }
        CONSTRUCT {
            (?X) log:allPossibleCases ().
        } WHERE {
            ?X a :Mortal.
        }
    } log:satisfiable false.
}
