#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/graph-reachability-test/graph-reachability.pl3 --output graph-reachability-output.pl3
