#!/bin/bash
eye "$@" --nope --tactic limited-answer 1 --wcache https://github.com/josd/eye/blob/master/reasoning/ea . --pl https://github.com/josd/eye/blob/master/reasoning/ea/ea_program.pl --query https://github.com/josd/eye/blob/master/reasoning/ea/ea_query.n3 > ea_answer.n3
