#!/bin/bash
eye "$@" --nope --tactic limited-answer 1 --wcache http://josd.github.io/eye/reasoning/ea . --pl http://josd.github.io/eye/reasoning/ea/ea_program.pl --query http://josd.github.io/eye/reasoning/ea/ea_query.n3 > ea_answer.n3
