#!/bin/bash
eye "$@" --nope --tactic limited-answer 1 --wcache https://raw.githubusercontent.com/josd/eye/master/reasoning/ea . --pl https://raw.githubusercontent.com/josd/eye/master/reasoning/ea/ea_program.pl --query https://raw.githubusercontent.com/josd/eye/master/reasoning/ea/ea_query.n3 > ea_answer.n3
