#!/bin/bash
eye "$@" --tactic limited-answer 1 https://raw.githubusercontent.com/josd/eye/master/reasoning/rs/randomsample-rule.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/rs/randomsample-query.n3 > randomsample-proof.n3
