#!/bin/bash
eye "$@" --tactic limited-answer 1 --n3 https://github.com/josd/eye/blob/master/reasoning/rs/randomsample-rule.n3 --query https://github.com/josd/eye/blob/master/reasoning/rs/randomsample-query.n3 > randomsample-proof.n3
