#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --tactic limited-answer 1 http://eyereasoner.github.io/eye/reasoning/rs/randomsample-rule.n3 --query http://eyereasoner.github.io/eye/reasoning/rs/randomsample-query.n3 --output randomsample-proof.n3
