#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/fallacy-detection-test/fallacy-detection.pl3 --output fallacy-detection-output.pl3
