#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --prolog https://eyereasoner.github.io/eye/reasoning/display-user-details/display-user-details.pl --output display-user-details-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --prolog https://eyereasoner.github.io/eye/reasoning/display-user-details/display-user-details.pl --output display-user-details-proof.n3
