#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/nexus .. --nope https://eyereasoner.github.io/eye/nexus/turing/turing-increment.ttl --sparql-backward https://eyereasoner.github.io/eye/nexus/turing/turing.rq --sparql-query https://eyereasoner.github.io/eye/nexus/turing/turing-query.rq --output turing-answer.ttl
