#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/control-system-test/control-system.pl3 --output control-system-output.pl3
