#!/bin/bash
echo "% Running TWO tests" | tee ./result/result.pl
echo "" | tee -a ./result/result.pl
for f in *.pl
do 
    ${1:-tpl} -g test "$f" | tee -a ./result/result.pl
    echo "" | tee -a ./result/result.pl
done
git diff
