#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/eulers-identity-test/eulers-identity.pl3 --output eulers-identity-output.pl3
