#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/beetle.n3 --output beetle-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/complex.n3 --output complex-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/edt.n3 --turtle http://eyereasoner.github.io/eye/reasoning/edt/test-facts.ttl --turtle http://eyereasoner.github.io/eye/reasoning/edt/test-dl.ttl --output edt-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/fibonacci.n3 --output fibonacci-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/graph.n3 --output graph-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/peano.n3 --output peano-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/policy.n3 --output policy-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/socrates.n3 --output socrates-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/nand/universal-statement.n3 --output universal-statement-answer.n3
