#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/de/de.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/de/deA.n3 --query https://github.com/josd/eye/blob/master/reasoning/de/deQ.n3 > deE.n3
