#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/de/de.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/de/deA.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/de/deQ.n3 > deE.n3
