#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --n3 https://eyereasoner.github.io/eye/reasoning/bnode-scope/test1.n3 --pass-only-new --output test1-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --n3 https://eyereasoner.github.io/eye/reasoning/bnode-scope/test1.n3 --pass-only-new --output test1-proof.n3
