#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/fib/fib.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/fib/fibQ.n3 > fibE.n3
eye "$@" --nope https://raw.githubusercontent.com/josd/eye/master/reasoning/fib/fib.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/fib/fibQ.n3 > fibA.n3
