#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/research/cs . --nope --turtle http://josd.github.io/eye/research/cs/data-001.n3 http://josd.github.io/eye/research/cs/rules-001.n3 --query http://josd.github.io/eye/research/cs/query-001.n3 > answer-001.n3
eye "$@" --wcache http://josd.github.io/eye/research/cs . --turtle http://josd.github.io/eye/research/cs/data-001.n3 http://josd.github.io/eye/research/cs/rules-001.n3 --query http://josd.github.io/eye/research/cs/query-001.n3 > proof-001.n3
