#!/bin/bash
eye "$@" --tactic limited-answer 1 --n3 https://github.com/josd/eye/blob/master/reasoning/dpe/dpe_theory.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/dpe/dpe_assumption.n3 --query https://github.com/josd/eye/blob/master/reasoning/dpe/dpe_query.n3 > dpe_proof.n3
