#!/bin/bash
eye "$@" --tactic limited-answer 1 https://raw.githubusercontent.com/josd/eye/master/reasoning/dpe/dpe_theory.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/dpe/dpe_assumption.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/dpe/dpe_query.n3 > dpe_proof.n3
