#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --tactic limited-answer 1 http://josd.github.io/eye/reasoning/dpe/dpe_theory.n3 http://josd.github.io/eye/reasoning/dpe/dpe_assumption.n3 --query http://josd.github.io/eye/reasoning/dpe/dpe_query.n3 --output dpe_proof.n3
