#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/enigma1225/enigma1225.n3 --query http://josd.github.io/eye/reasoning/enigma1225/enigma1225_query.n3 --output enigma1225_answer.n3
