#!/bin/bash
eye "$@" --nope --plugin http://josd.github.io/eye/reasoning/enigma1225/enigma1225_program.n3pl --query http://josd.github.io/eye/reasoning/enigma1225/enigma1225_query.n3 > enigma1225_answer.n3
