#!/bin/bash
eye "$@" --nope --wcache http://josd.github.io/eye/reasoning/enigma1225 . --pl http://josd.github.io/eye/reasoning/enigma1225/enigma1225_program.pl --query http://josd.github.io/eye/reasoning/enigma1225/enigma1225_query.n3 > enigma1225_answer.n3

