#!/bin/bash
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --quiet --nope examples/socrates.n3 --query examples/socrates-query.n3 > examples/socrates-answer.n3
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --quiet examples/socrates.n3 --query examples/socrates-query.n3 > examples/socrates-proof.n3
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --quiet --nope examples/gps-plugin.n3 examples/gps-example1.n3 --query examples/gps-query1.n3 > examples/gps-answer.n3
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --quiet --nope examples/dt-rules.n3 examples/dt-facts.n3 --query examples/dt-query.n3 > examples/dt-answer.n3
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --quiet --nope examples/complex.n3 --query examples/complex-query.n3 > examples/complex-answer.n3
