#!/bin/bash
eye "$@" --nope --plugin http://josd.github.io/eye/reasoning/utm/utm_interpreter.eyepl --plugin http://josd.github.io/eye/reasoning/utm/utm_program.eyepl --query http://josd.github.io/eye/reasoning/utm/utm_query.n3 > utm_answer.n3
eye "$@" --plugin http://josd.github.io/eye/reasoning/utm/utm_interpreter.eyepl --plugin http://josd.github.io/eye/reasoning/utm/utm_program.eyepl --query http://josd.github.io/eye/reasoning/utm/utm_query.n3 > utm_proof.n3
