#!/bin/bash
eye "$@" --nope --pl https://github.com/josd/eye/blob/master/reasoning/utm/utm_interpreter.pl --pl https://github.com/josd/eye/blob/master/reasoning/utm/utm_program.pl --query https://github.com/josd/eye/blob/master/reasoning/utm/utm_query.n3 > utm_answer.n3
eye "$@" --pl https://github.com/josd/eye/blob/master/reasoning/utm/utm_interpreter.pl --pl https://github.com/josd/eye/blob/master/reasoning/utm/utm_program.pl --query https://github.com/josd/eye/blob/master/reasoning/utm/utm_query.n3 > utm_proof.n3
