#!/bin/bash
eye "$@" --nope --prolog http://josd.github.io/eye/reasoning/utm/utm_interpreter.pl --prolog http://josd.github.io/eye/reasoning/utm/utm_program.pl --query http://josd.github.io/eye/reasoning/utm/utm_query.n3 > utm_answer.n3
eye "$@" --prolog http://josd.github.io/eye/reasoning/utm/utm_interpreter.pl --prolog http://josd.github.io/eye/reasoning/utm/utm_program.pl --query http://josd.github.io/eye/reasoning/utm/utm_query.n3 > utm_proof.n3
