:- op(1200, xfx, :+).

answer('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#angers>', '<https://eyereasoner.github.io/ns#nantes>')).
answer('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#nantes>')).
answer('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#nantes>')).
answer('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#nantes>')).

% proof steps
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#orleans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#orleans>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#chartres>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#chartres>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#amiens>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#amiens>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#blois>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#blois>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#bourges>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#bourges>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#blois>', '<https://eyereasoner.github.io/ns#tours>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#blois>', '<https://eyereasoner.github.io/ns#tours>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#lemans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#lemans>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#angers>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#angers>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#tours>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#tours>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#oneway>'(A, B)), '<https://eyereasoner.github.io/ns#oneway>'('<https://eyereasoner.github.io/ns#angers>', '<https://eyereasoner.github.io/ns#nantes>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#angers>', '<https://eyereasoner.github.io/ns#nantes>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#orleans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#blois>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#blois>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#orleans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#bourges>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#bourges>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#chartres>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#lemans>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#lemans>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#blois>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#blois>', '<https://eyereasoner.github.io/ns#tours>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#tours>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#lemans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#angers>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#angers>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#lemans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#tours>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#tours>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#angers>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#angers>', '<https://eyereasoner.github.io/ns#nantes>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#nantes>')).
step((true:+'<https://eyereasoner.github.io/ns#path>'(_, '<https://eyereasoner.github.io/ns#nantes>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#angers>', '<https://eyereasoner.github.io/ns#nantes>'), true).
step((true:+'<https://eyereasoner.github.io/ns#path>'(_, '<https://eyereasoner.github.io/ns#nantes>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#nantes>'), true).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#orleans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#orleans>', '<https://eyereasoner.github.io/ns#tours>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#tours>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#chartres>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#angers>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#angers>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#lemans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#nantes>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#nantes>')).
step(('<https://eyereasoner.github.io/ns#path>'(A, B):+'<https://eyereasoner.github.io/ns#path>'(A, C), '<https://eyereasoner.github.io/ns#path>'(C, B)), ('<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#lemans>'), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#lemans>', '<https://eyereasoner.github.io/ns#nantes>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#nantes>')).
step((true:+'<https://eyereasoner.github.io/ns#path>'(_, '<https://eyereasoner.github.io/ns#nantes>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#chartres>', '<https://eyereasoner.github.io/ns#nantes>'), true).
step((true:+'<https://eyereasoner.github.io/ns#path>'(_, '<https://eyereasoner.github.io/ns#nantes>')), '<https://eyereasoner.github.io/ns#path>'('<https://eyereasoner.github.io/ns#paris>', '<https://eyereasoner.github.io/ns#nantes>'), true).
