#!/bin/bash
eye "$@"  http://josd.github.io/eye/reasoning/rpo/food-example.n3  http://josd.github.io/eye/reasoning/rpo/food.n3  http://josd.github.io/eye/reasoning/rpo/rdfs-subClassOf.n3 --query http://josd.github.io/eye/reasoning/rpo/food-query.n3 > food-proof.n3
