#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/rpo/food-example.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/rpo/food.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/rpo/rdfs-subClassOf.n3 --query https://github.com/josd/eye/blob/master/reasoning/rpo/food-query.n3 > food-proof.n3
