#!/bin/bash
eye "$@" --n3p https://github.com/josd/eye/blob/master/reasoning/n3p/simple.ttl > simple.n3p
eye "$@" --n3p https://github.com/josd/eye/blob/master/reasoning/n3p/extra.ttl > extra.n3p
eye "$@" --n3p https://github.com/josd/eye/blob/master/reasoning/n3p/literals.ttl > literals.n3p
eye "$@" --n3p https://github.com/josd/eye/blob/master/reasoning/n3p/sample.n3 > sample.n3p
