#!/bin/bash
eye "$@" --n3p http://josd.github.io/eye/reasoning/n3p/simple.ttl > simple.pl
eye "$@" --n3p http://josd.github.io/eye/reasoning/n3p/extra.ttl > extra.pl
eye "$@" --n3p http://josd.github.io/eye/reasoning/n3p/literals.ttl > literals.pl
eye "$@" --n3p http://josd.github.io/eye/reasoning/n3p/sample.n3 > sample.pl
