#!/bin/bash
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/simple.pl --pass > simple-roundtrip-proof.ttl
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/extra.pl --pass > extra-roundtrip-proof.ttl
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/literals.pl --pass > literals-roundtrip-proof.ttl
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/sample.pl --pass-all > sample-roundtrip-proof.n3
