#!/bin/bash
eye "$@" --nope --prolog http://josd.github.io/eye/reasoning/n3p/simple.pl --pass > simple-roundtrip.ttl
eye "$@" --nope --prolog http://josd.github.io/eye/reasoning/n3p/extra.pl --pass > extra-roundtrip.ttl
eye "$@" --nope --prolog http://josd.github.io/eye/reasoning/n3p/literals.pl --pass > literals-roundtrip.ttl
eye "$@" --nope --prolog http://josd.github.io/eye/reasoning/n3p/sample.pl --pass-all > sample-roundtrip.n3
