#!/bin/bash
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/simple.n3p --pass > simple-roundtrip-proof.ttl
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/extra.n3p --pass > extra-roundtrip-proof.ttl
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/literals.n3p --pass > literals-roundtrip-proof.ttl
eye "$@" --plugin http://josd.github.io/eye/reasoning/n3p/sample.n3p --pass-all > sample-roundtrip-proof.n3
