#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/hanoi/hanoi.n3 --pass > hanoiA.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/hanoi/hanoi.n3 --pass > hanoiE.n3
