#!/bin/bash
eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/hanoi/hanoi.n3 --pass > hanoiA.n3
eye "$@" https://github.com/josd/eye/blob/master/reasoning/hanoi/hanoi.n3 --pass > hanoiE.n3
