#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let .. --nope --sparql-backward https://eyereasoner.github.io/eye/let/peano/peano.rq --sparql-query https://eyereasoner.github.io/eye/let/peano/peano-query.rq --output peano-answer.ttl
