#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/eyelet .. --nope https://eyereasoner.github.io/eye/eyelet/slide33/slide33.ttl --output slide33-answer.ttl
