#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/complex/complex.n3 --query http://josd.github.io/eye/reasoning/complex/complex_query.n3 > complex_answer.n3
