#!/bin/bash
eye "$@" --nope --wcache http://josd.github.io/eye/reasoning/complex . --query http://josd.github.io/eye/reasoning/complex/complex_query.n3 > complex_answer.n3
eye "$@" --nope --wcache http://josd.github.io/eye/reasoning/complex . --pl http://josd.github.io/eye/reasoning/complex/complex_query.pl > complex_answer2.n3
