#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --hmac-key k123 https://eyereasoner.github.io/eye/color/crypto/cryptoP.n3 --pass --output crypto-proof.n3
