#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/argus .. --nope https://eyereasoner.github.io/eye/argus/3outof5/3outof5.ttl --output 3outof5-answer.ttl
