#!/bin/bash
riot --stream=Turtle https://w3c.github.io/rdf-star/tests/semantics/manifest.jsonld | eye --quiet --nope https://w3c.github.io/rdf-star/tests/turtle/syntax/manifest.ttl - --query run-manifest.n3 > run-outcome.n3
