#!/bin/bash
riot --stream=Turtle https://w3c.github.io/rdf-star/tests/semantics/manifest.jsonld | eye --quiet --nope https://w3c.github.io/rdf-star/tests/turtle/syntax/manifest.ttl - --query run-manifest.n3 | tee run-outcome.n3
echo "#=============" | tee -a run-outcome.n3
echo "#TEST RDF-STAR" | tee -a run-outcome.n3
echo "#=============" | tee -a run-outcome.n3
echo -n "#FAILED: " | tee -a run-outcome.n3; cat run-outcome.n3 | grep :failed | wc -l | tee -a run-outcome.n3
echo -n "#PASSED: " | tee -a run-outcome.n3; cat run-outcome.n3 | grep :passed | wc -l | tee -a run-outcome.n3
