#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --turtle https://eyereasoner.github.io/eye/reasoning/path-discovery-test/path-discovery-data.ttl --pl3 https://eyereasoner.github.io/eye/reasoning/path-discovery-test/path-discovery.pl3 --output path-discovery-output.pl3
