#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/skos/skos-mapping-sample-snomed-icd10.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/skos/skos-mapping-validation-rules.n3 --query https://github.com/josd/eye/blob/master/reasoning/skos/skos-mapping-validation-query.n3 > skos_mv_proof.n3
