#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/skos/skos-mapping-sample-snomed-icd10.n3 http://josd.github.io/eye/reasoning/skos/skos-mapping-validation-rules.n3 --query http://josd.github.io/eye/reasoning/skos/skos-mapping-validation-query.n3 --output skos_mv_proof.n3
