#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/deontic-logic-test/deontic-logic.pl3 --output deontic-logic-output.pl3
