#!/bin/bash
# -------------
# EYE resources
# -------------

pushd ~/github.com/josd/eye/resources
echo -n > resources.txt
echo "# $(date)" > resources.diff
IMATCH="^diff|^index|^Binary|^--|^\+-|\+\+|^@@|#Processed by|#DONE|in=|#ENDS"

for dir in */
do
    pushd ${dir}
    ./test |& tee -a ../resources.txt
    git diff -U0 . | grep -E -v "$IMATCH" >> ../resources.diff
    popd
done

eye  resources.diff --pass > /dev/null
popd
