#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --query https://eyereasoner.github.io/eye/reasoning/newton-raphson/newton-raphson-query.n3 --output newton-raphson-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --query https://eyereasoner.github.io/eye/reasoning/newton-raphson/newton-raphson-query.n3 --output newton-raphson-proof.n3
