#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/glass/test.n3 --query https://eyereasoner.github.io/eye/color/glass/testQ.n3 --output testA.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/glass/test.n3 --query https://eyereasoner.github.io/eye/color/glass/testQ.n3 --output testE.n3
