#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/healthcare-access-control-test/healthcare-access-control.pl3 --output healthcare-access-control-output.pl3
