#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --tactic limited-answer 1 https://eyereasoner.github.io/eye/reasoning/restpath/initial.n3 https://eyereasoner.github.io/eye/reasoning/restpath/path-9-3.n3 --query https://eyereasoner.github.io/eye/reasoning/restpath/goal.n3 --output path-9-3-proof.n3
