#!/bin/bash
eye "$@" --nope https://raw.githubusercontent.com/josd/eye/master/reasoning/polygon/polygon.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/polygon/polygon_query.n3 > polygon_answer.n3
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/polygon/polygon.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/polygon/polygon_query.n3 > polygon_proof.n3
