#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/polygon/polygon.n3 --query http://eyereasoner.github.io/eye/reasoning/polygon/polygon_query.n3 --output polygon_answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/polygon/polygon.n3 --query http://eyereasoner.github.io/eye/reasoning/polygon/polygon_query.n3 --output polygon_proof.n3
