#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/polygon . --nope http://josd.github.io/eye/reasoning/polygon/polygon.n3 --query http://josd.github.io/eye/reasoning/polygon/polygon_query.n3 > polygon_answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning/polygon . http://josd.github.io/eye/reasoning/polygon/polygon.n3 --query http://josd.github.io/eye/reasoning/polygon/polygon_query.n3 > polygon_proof.n3
