#!/bin/bash
for file in *.ttl
do
    echo $file
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --turtle https://eyereasoner.github.io/eye/reasoning/surfaces/$file --output output/$file
done
