#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/combinatorics-test/combinatorics.pl3 --output combinatorics-output.pl3
