#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope --tactic limited-answer 5 https://eyereasoner.github.io/eye/color/mi/mi.n3 --query https://eyereasoner.github.io/eye/color/mi/mi-query.n3 --output mi-answer.n3
