#!/bin/bash
echo -n "" | tee result.pl
for f in examples/*.pl
do
    echo "% running $f" | tee -a result.pl
    scryer-prolog -g "run,halt" webeye.pl "$f" | tee -a result.pl
    echo "" | tee -a result.pl
done
