#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/conflict-resolution-test/conflict-resolution.pl3 --output conflict-resolution-output.pl3
