#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/gps/gps-plugin.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/gps/gps-example1.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/gps/gps-query1.n3 > gps-proof1.n3
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/gps/gps-plugin.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/gps/gps-example2.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/gps/gps-query2.n3 > gps-proof2.n3
