#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
DIFF=0

echo -e "${YELLOW}-------------------------------------------------${NORMAL}"
echo -e "${YELLOW}running eyelet-rust examples and test cases${NORMAL}"
echo -e "${YELLOW}using cargo v$(cargo --version | awk '{ print $2 }')${NORMAL}"
echo -e "${YELLOW}-------------------------------------------------${NORMAL}"
echo ""

pad () {
    [ "$#" -gt 1 ]
    [ -n "$2" ]
    printf "%$2.${2#-}s" "$1"
}

begin=$(($(date +%s)))
for dir in */
do
    pushd "${dir}" > /dev/null
    echo -en "$(pad "${file}${dir}" -34)"
    start=$(($(date +%s%N)/1000000))
    cargo run --release > output.txt 2> /dev/null
    end=$(($(date +%s%N)/1000000))
    echo -en "${YELLOW}$(pad "`expr $end - $start` msec" 12)${NORMAL} "
    if [[ $(git diff . | wc -l) -eq 0 ]]; then
        echo -e "${GREEN}OK${NORMAL}"
        ((OK++))
    else
        echo -e "${RED}DIFF${NORMAL}"
        ((DIFF++))
    fi
    popd  > /dev/null
done
end=$(($(date +%s)))
echo ""

echo -e "${YELLOW}`expr $end - $begin` sec${NORMAL} ${GREEN}${OK} OK${NORMAL} ${RED}${DIFF} DIFF${NORMAL}"
if [[ ${DIFF} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
