#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let-turtle .. --nope https://eyereasoner.github.io/eye/let-turtle/wet/wet.ttl --output wet-answer.ttl
