#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/proof-by-contradiction-test/proof-by-contradiction.pl3 --output proof-by-contradiction-output.pl3 2> proof-by-contradiction-output.err
