#!/bin/bash
eye --quiet --nope \
    https://w3c.github.io/rdf-tests/rdf/rdf12/rdf-n-triples/syntax/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-triples/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf12/rdf-n-quads/syntax/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-n-quads/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf12/rdf-semantics/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf12/rdf-turtle/eval/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf12/rdf-turtle/syntax/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-turtle/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf12/rdf-trig/eval/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf12/rdf-trig/syntax/manifest.ttl \
    https://w3c.github.io/rdf-tests/rdf/rdf11/rdf-trig/manifest.ttl \
    --query run-manifest.n3 --output run-outcome.n3

echo "# ============" | tee -a run-outcome.n3
echo "# TEST RDF 1.2" | tee -a run-outcome.n3
echo "# ============" | tee -a run-outcome.n3
echo "#"
echo -n "# RESULT: " | tee -a run-outcome.n3; cat run-outcome.n3 | grep :result | wc -l | tee -a run-outcome.n3
echo -n "# PASSED: " | tee -a run-outcome.n3; cat run-outcome.n3 | grep :passed | wc -l | tee -a run-outcome.n3
echo -n "# FAILED: " | tee -a run-outcome.n3; cat run-outcome.n3 | grep :failed | wc -l | tee -a run-outcome.n3
