#!/bin/bash

# -------------------
# EYE imagining tests
# -------------------

pushd ~/github.com/josd/eye/imagining
echo -n > imagining.txt
echo "# $(date)" > imagining.diff
IMATCH="^diff|^index|^Binary|^--|^\+-|\+\+|^@@|#Processed by|#DONE|in=|#ENDS"

pushd bell; ./test "$@" 2>&1 | tee -a ../imagining.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../imagining.diff; popd
pushd easter; ./test "$@" 2>&1 | tee -a ../imagining.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../imagining.diff; popd
pushd euler; ./test "$@" 2>&1 | tee -a ../imagining.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../imagining.diff; popd
pushd fibonacci; ./test "$@" 2>&1 | tee -a ../imagining.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../imagining.diff; popd
pushd grover; ./test "$@" 2>&1 | tee -a ../imagining.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../imagining.diff; popd

eye --n3 imagining.diff --pass > /dev/null
popd
