#!/bin/bash
for f in *.trig
do
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --trig http://eyereasoner.github.io/eye/reasoning/lingua/$f --output output/$f
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --trig http://eyereasoner.github.io/eye/reasoning/lingua/$f --output proof/$f
done
