#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
FAILED=0

echo -e "${YELLOW}Running eye/logic3/test${NORMAL}"
echo ""

for f in *.n3
do
    eye --quiet --nope --skolem-genid 09856efc-a6d2-4575-95b6-a22fd5d3c9c9 $f --output out/$f.out
    if [[ $(git diff out/$f.out | wc -l) -ne 0 ]]; then
        echo -e "$f ${RED}FAILED${NORMAL}"
        ((FAILED++))
    else
        echo -e "$f ${GREEN}OK${NORMAL}"
        ((OK++))
    fi
done
echo ""

echo -e "Tests: ${GREEN}${OK} OK${NORMAL} ${RED}${FAILED} FAILED${NORMAL}"

if [[ ${FAILED} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
