#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/twf/example27.n3 --pass --output example27-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/twf/example27.n3 --pass --output example27-proof.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/twf/example28.n3 --pass --output example28-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/twf/example28.n3 --pass --output example28-proof.n3
