#!/bin/bash
eye "$@" --nope --pl https://raw.githubusercontent.com/josd/eye/master/reasoning/sudoku/sudoku_program.pl --query https://raw.githubusercontent.com/josd/eye/master/reasoning/sudoku/sudoku_query.n3 > sudoku_answer.n3
eye "$@" --pl https://raw.githubusercontent.com/josd/eye/master/reasoning/sudoku/sudoku_program.pl --query https://raw.githubusercontent.com/josd/eye/master/reasoning/sudoku/sudoku_query.n3 > sudoku_proof.n3
