#!/bin/bash
eye "$@" --nope --plugin http://josd.github.io/eye/reasoning/sudoku/sudoku_program.eyepl --query http://josd.github.io/eye/reasoning/sudoku/sudoku_query.n3 > sudoku_answer.n3
eye "$@" --plugin http://josd.github.io/eye/reasoning/sudoku/sudoku_program.eyepl --query http://josd.github.io/eye/reasoning/sudoku/sudoku_query.n3 > sudoku_proof.n3
