#!/bin/bash
eye "$@" --nope --pl https://github.com/josd/eye/blob/master/reasoning/sudoku/sudoku_program.pl --query https://github.com/josd/eye/blob/master/reasoning/sudoku/sudoku_query.n3 > sudoku_answer.n3
eye "$@" --pl https://github.com/josd/eye/blob/master/reasoning/sudoku/sudoku_program.pl --query https://github.com/josd/eye/blob/master/reasoning/sudoku/sudoku_query.n3 > sudoku_proof.n3
