#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning/arcus .. --nope https://eyereasoner.github.io/eye/reasoning/arcus/access-control-policy/access-control-policy.ttl --output access-control-policy-answer.ttl
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning/arcus .. https://eyereasoner.github.io/eye/reasoning/arcus/access-control-policy/access-control-policy.ttl --output access-control-policy-proof.ttl
