#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/peasant/peasant.n3 --query https://eyereasoner.github.io/eye/reasoning/peasant/peasant-query.n3 --output peasant-answer.n3
