#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/hamiltonian-path-test/hamiltonian-path.pl3 --output hamiltonian-path-output.pl3
