#!/bin/bash
eye --quiet --nope https://w3c.github.io/rdf-tests/turtle/manifest.ttl --query run-manifest.n3 | tee run-outcome.n3
echo "#===============" | tee -a run-outcome.n3
echo "#TEST TURTLE-DEV" | tee -a run-outcome.n3
echo "#===============" | tee -a run-outcome.n3
echo -n "#FAILED: " | tee -a run-outcome.n3; cat run-outcome.n3 | grep :FAILED | wc -l | tee -a run-outcome.n3
echo -n "#PASSED: " | tee -a run-outcome.n3; cat run-outcome.n3 | grep :PASSED | wc -l | tee -a run-outcome.n3
