#!/bin/bash
cat multi-query | eye "$@" --wcache https://raw.githubusercontent.com/josd/eye/master/reasoning/mq . --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/mq/data.n3 --multi-query > mq_proof.n3
