#!/bin/bash
cat multi-query | eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --blogic --turtle http://eyereasoner.github.io/eye/reasoning/mq/data.ttl --multi-query --output mq-answer.n3
