#!/bin/bash
cat multi-query | eye "$@" --wcache https://github.com/josd/eye/blob/master/reasoning/mq . --turtle https://github.com/josd/eye/blob/master/reasoning/mq/data.n3 --multi-query > mq_proof.n3
