#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/seq . --nope http://josd.github.io/eye/reasoning/seq/seq_components.n3 --query http://josd.github.io/eye/reasoning/seq/seq_query.n3 > seq_answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning/seq . http://josd.github.io/eye/reasoning/seq/seq_components.n3 --query http://josd.github.io/eye/reasoning/seq/seq_query.n3 > seq_proof.n3
