#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/seq/seq_components.n3 --query http://eyereasoner.github.io/eye/reasoning/seq/seq_query.n3 --output seq_answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/seq/seq_components.n3 --query http://eyereasoner.github.io/eye/reasoning/seq/seq_query.n3 --output seq_proof.n3
