#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --turtle https://eyereasoner.github.io/eye/reasoning/lubm-test/lubm-data.ttl --pl3 https://eyereasoner.github.io/eye/reasoning/lubm-test/lubm.pl3 --output lubm-output.pl3
