#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --tactic limited-answer 1 http://josd.github.io/eye/reasoning/usm/usmP.n3 --query http://josd.github.io/eye/reasoning/usm/usmQ.n3 --output usmE.n3
