#!/bin/bash
eye "$@" --tactic limited-answer 1 https://raw.githubusercontent.com/josd/eye/master/reasoning/usm/usmP.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/usm/usmQ.n3 > usmE.n3
