#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --tactic limited-answer 1 http://eyereasoner.github.io/eye/reasoning/usm/usmP.n3 --query http://eyereasoner.github.io/eye/reasoning/usm/usmQ.n3 --output usmE.n3
