#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/display-user-details-test/display-user-details.pl3 --output display-user-details-output.pl3
