#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/rgb/redgraph001.n3 --query http://eyereasoner.github.io/eye/reasoning/rgb/greenquery001.n3 --output blueproof001.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/rgb/redgraph002.n3 --query http://eyereasoner.github.io/eye/reasoning/rgb/greenquery002.n3 --output blueproof002.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/rgb/redgraph003.n3 --query http://eyereasoner.github.io/eye/reasoning/rgb/greenquery003.n3 --output blueproof003.n3
