#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/rgb/redgraph001.n3 --query http://josd.github.io/eye/reasoning/rgb/greenquery001.n3 > blueproof001.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/rgb/redgraph002.n3 --query http://josd.github.io/eye/reasoning/rgb/greenquery002.n3 > blueproof002.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/rgb/redgraph003.n3 --query http://josd.github.io/eye/reasoning/rgb/greenquery003.n3 > blueproof003.n3
