#!/bin/bash
eye "$@" https://github.com/josd/eye/blob/master/reasoning/rgb/redgraph001.n3 --query https://github.com/josd/eye/blob/master/reasoning/rgb/greenquery001.n3 > blueproof001.n3
eye "$@" https://github.com/josd/eye/blob/master/reasoning/rgb/redgraph002.n3 --query https://github.com/josd/eye/blob/master/reasoning/rgb/greenquery002.n3 > blueproof002.n3
eye "$@" https://github.com/josd/eye/blob/master/reasoning/rgb/redgraph003.n3 --query https://github.com/josd/eye/blob/master/reasoning/rgb/greenquery003.n3 > blueproof003.n3
