#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/resto . --tactic limited-answer 1 http://josd.github.io/eye/reasoning/resto/resto.n3 --query http://josd.github.io/eye/reasoning/resto/restoG.n3 > resto-proof.n3
