#!/bin/bash
eye "$@" --tactic limited-answer 1 --n3 https://github.com/josd/eye/blob/master/reasoning/resto/resto.n3 --query https://github.com/josd/eye/blob/master/reasoning/resto/restoG.n3 > resto-proof.n3
