#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --tactic limited-answer 1 https://eyereasoner.github.io/eye/reasoning/resto/resto.n3 --query https://eyereasoner.github.io/eye/reasoning/resto/restoG.n3 --output resto-proof.n3
