#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/socrates-star/socrates.n3 --query https://eyereasoner.github.io/eye/color/qgen/qgen.n3 --output query.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/socrates-star/socrates.n3 --query https://eyereasoner.github.io/eye/color/qgen/query.n3 --output answer.n3
