#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let .. --nope https://eyereasoner.github.io/eye/let/context-associations/context-associations.ttl --sparql-query https://eyereasoner.github.io/eye/let/context-associations/context-associations-query.rq --output context-associations-answer.ttl
