#!/bin/bash -x
eye --quiet --nope union.ttl --output out/union.ttl.out
eye --quiet --nope append.ttl --output out/append.ttl.out
eye --quiet --nope lott.ttl --output out/lott.ttl.out
eye --quiet --nope out/lott.ttl.out --output out/lott.ttl.out.out
