#!/bin/bash
eye gentf.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/edt/test-dl.n3 http://josd.github.io/eye/reasoning/edt/test-rules.n3 --image edtpe.pvm
