#!/bin/bash
eye gentf.n3
eye "$@" --quiet --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/edt/test-dl.n3 --query http://josd.github.io/eye/reasoning/edt/parteval-subclass.n3 > test-edt.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --no-distinct-input http://josd.github.io/eye/reasoning/edt/test-edt.n3 --image edtpe.pvm
