#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --turtle http://eyereasoner.github.io/eye/reasoning/edt/test-facts.ttl --turtle http://eyereasoner.github.io/eye/reasoning/edt/test-dl.ttl http://eyereasoner.github.io/eye/reasoning/edt/test-rules.n3 --query http://eyereasoner.github.io/eye/reasoning/edt/test-query.n3 --output test-answer.n3
