#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/gray-code-counter-test/gray-code-counter.pl3 --output gray-code-counter-output.pl3
