#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/derivative/derivative.n3 --query http://josd.github.io/eye/reasoning/derivative/derivative_query.n3 > derivative_answer.n3
