#!/bin/bash
eye "$@" --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/h2o/hypothesis-001.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/h2o/data-001.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/h2o/rules-001.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/h2o/query-001.n3 > proof-001.n3
