#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/reif/data.n3 https://eyereasoner.github.io/eye/color/reif/reify.n3 --pass --output data-reif.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/reif/data-reif.n3 https://eyereasoner.github.io/eye/color/reif/dereify.n3 --pass --output data-roundtrip.n3
