#!/bin/bash
for f in *.n3
do
    if [ "$f" != "sequents.n3" ]; then
        echo + eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/sequents/$f https://eyereasoner.github.io/eye/reasoning/sequents/sequents.n3 --output answer/$f
        eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/sequents/$f https://eyereasoner.github.io/eye/reasoning/sequents/sequents.n3 --output answer/$f
        echo + eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. https://eyereasoner.github.io/eye/reasoning/sequents/$f https://eyereasoner.github.io/eye/reasoning/sequents/sequents.n3 --output proof/$f
        eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. https://eyereasoner.github.io/eye/reasoning/sequents/$f https://eyereasoner.github.io/eye/reasoning/sequents/sequents.n3 --output proof/$f
    fi
done
