#!/bin/bash
for f in *.n3
do
    echo + eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --nope $f --pass-only-new --output $f.out
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --nope $f --pass-only-new --output $f.out
done
