#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/sequents/beetle.n3 --query http://eyereasoner.github.io/eye/reasoning/sequents/beetle-query.n3 --output beetle-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/sequents/beetle12.n3 --query http://eyereasoner.github.io/eye/reasoning/sequents/beetle-query.n3 --output beetle12-answer.n3
