#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/rpo/food-example.n3 https://eyereasoner.github.io/eye/color/rpo/food.n3 https://eyereasoner.github.io/eye/color/rpo/rdfs-subClassOf.n3 --query https://eyereasoner.github.io/eye/color/rpo/food-query.n3 --output food-proof.n3
