#!/bin/bash
eye "$@" --nope https://raw.githubusercontent.com/josd/eye/master/reasoning/easter/easterP.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/easter/easterF.n3 > easterA.n3
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/easter/easterP.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/easter/easterF.n3 > easterE.n3

