#!/bin/bash
eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/easter/easterP.n3 --query https://github.com/josd/eye/blob/master/reasoning/easter/easterF.n3 > easterA.n3
eye "$@" https://github.com/josd/eye/blob/master/reasoning/easter/easterP.n3 --query https://github.com/josd/eye/blob/master/reasoning/easter/easterF.n3 > easterE.n3

