#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/easter . --nope http://josd.github.io/eye/reasoning/easter/easterP.n3 --query http://josd.github.io/eye/reasoning/easter/easterF.n3 > easterA.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning/easter . http://josd.github.io/eye/reasoning/easter/easterP.n3 --query http://josd.github.io/eye/reasoning/easter/easterF.n3 > easterE.n3

