#!/bin/bash
curl -s -L http://josd.github.io/eye/reasoning/streason/graph-10.n3 | eye "$@" --nope  http://josd.github.io/eye/reasoning/streason/streason-rules.n3 --turtle - --streaming-reasoning > streason-output.n3
