#!/bin/bash
cat graph-10.n3 | eye "$@" --wcache http://josd.github.io/eye/reasoning/streason . --nope http://josd.github.io/eye/reasoning/streason/streason-rules.n3 --turtle - --streaming-reasoning > streason-output.n3
