#!/bin/bash
curl -s -L https://github.com/josd/eye/blob/master/reasoning/streason/graph-10.n3 | eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/streason/streason-rules.n3 --turtle - --streaming-reasoning > streason-output.n3
