#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/eyelet .. --nope https://eyereasoner.github.io/eye/eyelet/takeuchi/takeuchi.ttl --output takeuchi-answer.ttl
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/eyelet .. https://eyereasoner.github.io/eye/eyelet/takeuchi/takeuchi.ttl --output takeuchi-proof.ttl
