#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/control-system/data.ttl --sparql-backward https://eyereasoner.github.io/eye/reasoning/control-system/rules.rq --query https://eyereasoner.github.io/eye/reasoning/control-system/query.rq --output answer.ttl
