#!/bin/bash
pushd ~/github.com/josd/trealla
git pull upstream master
git push origin master
make clean
make
make test
popd
echo
pushd ~/github.com/josd/eye/reasoning/retina
echo
echo "============================"
echo "Testing eye/reasoning/retina"
echo "============================"
echo
./run-test
echo -n "FAILED: "; cat run-outcome.n3 | grep FAILED | wc -l
echo -n "PASSED: "; cat run-outcome.n3 | grep PASSED | wc -l
popd
