#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --tactic limited-answer 1 http://eyereasoner.github.io/eye/reasoning/diamond-property/diamond-property.n3 --output diamond-property-answer.n3
