#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/monkey-bananas-test/monkey-bananas.pl3 --output monkey-bananas-output.pl3
