#!/bin/bash
echo "PREFIX : <http://josd.github.io/eye/reasoning#>" | tee result.n3
echo "" | tee -a result.n3
for f in *.pl
do
    swipl -g test "$f" | tee -a result.n3
    echo "" | tee -a result.n3
done
