#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/gcc/gcc.n3 --query http://josd.github.io/eye/reasoning/gcc/gccQ.n3 --output gccA.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/gcc/gcc.n3 --query http://josd.github.io/eye/reasoning/gcc/gccQ.n3 --output gccE.n3
