#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/gcc/gcc.n3 --query https://eyereasoner.github.io/eye/reasoning/gcc/gccQ.n3 --output gccA.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. https://eyereasoner.github.io/eye/reasoning/gcc/gcc.n3 --query https://eyereasoner.github.io/eye/reasoning/gcc/gccQ.n3 --output gccE.n3
