#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/gcc/gcc.n3 --query http://eyereasoner.github.io/eye/reasoning/gcc/gccQ.n3 --output gccA.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/gcc/gcc.n3 --query http://eyereasoner.github.io/eye/reasoning/gcc/gccQ.n3 --output gccE.n3
