#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/nexus .. --nope https://eyereasoner.github.io/eye/nexus/good-cobbler/good-cobbler.ttl --sparql-query https://eyereasoner.github.io/eye/nexus/good-cobbler/good-cobbler-query.rq --output good-cobbler-answer.ttl
