#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/nexus .. --nope https://eyereasoner.github.io/eye/nexus/fuse/fuse.ttl https://eyereasoner.github.io/eye/nexus/fuse/fuse.rq 2> fuse-output.err
