#!/bin/bash -x
eye --quiet --nope append.ttl --output out/append.ttl.out
eye --quiet --nope lott.ttl --output out/lott.ttl.out
eye --quiet --nope sha512.ttl --output out/sha512.ttl.out
eye --quiet --nope socrates-contradiction.ttl 2> out/socrates-contradiction.ttl.out
eye --quiet --nope union.ttl --output out/union.ttl.out
