#!/bin/bash -x
eye --quiet --nope append.ttl --output out/append.ttl.out
eye --quiet --nope backward.ttl --output out/backward.ttl.out
eye --quiet --nope forward.ttl --output out/forward.ttl.out
eye --quiet --nope gen.ttl --output out/gen.ttl.out
eye --quiet --nope sha512.ttl --output out/sha512.ttl.out
eye --quiet --nope socrates-contradiction.ttl 2> out/socrates-contradiction.ttl.out
eye --quiet --nope union.ttl --output out/union.ttl.out
