#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/kaprekar-constant-test/kaprekar-constant.pl3 --output kaprekar-constant-output.pl3
