#!/bin/bash
eye "$@" --nope --n3 http://josd.github.io/eye/reasoning/csv/select-data.n3 --query http://josd.github.io/eye/reasoning/csv/select-query.n3 --strings > select-data.csv
eye "$@" --n3 http://josd.github.io/eye/reasoning/csv/select-data.n3 --query http://josd.github.io/eye/reasoning/csv/select-query.n3 > select-proof.n3
eye "$@" --n3 http://josd.github.io/eye/reasoning/csv/select-data-extra.n3 --query http://josd.github.io/eye/reasoning/csv/select-query.n3 > select-proof-extra.n3
