#!/bin/bash
eye "$@" --nope https://github.com/josd/eye/blob/master/reasoning/csv/select-data.n3 --query https://github.com/josd/eye/blob/master/reasoning/csv/select-query.n3 --strings > select-data.csv
eye "$@" https://github.com/josd/eye/blob/master/reasoning/csv/select-data.n3 --query https://github.com/josd/eye/blob/master/reasoning/csv/select-query.n3 > select-proof.n3
eye "$@" https://github.com/josd/eye/blob/master/reasoning/csv/select-data-extra.n3 --query https://github.com/josd/eye/blob/master/reasoning/csv/select-query.n3 > select-proof-extra.n3
