#!/bin/bash
eye "$@" --turtle https://github.com/josd/eye/blob/master/reasoning/cs/data-001.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/cs/rules-001.n3 --query https://github.com/josd/eye/blob/master/reasoning/cs/query-001.n3 > proof-001.n3
