#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/cs/data-001.n3 http://josd.github.io/eye/reasoning/cs/rules-001.n3 --query http://josd.github.io/eye/reasoning/cs/query-001.n3 --output answer-001.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/cs/data-001.n3 http://josd.github.io/eye/reasoning/cs/rules-001.n3 --query http://josd.github.io/eye/reasoning/cs/query-001.n3 --output proof-001.n3
