#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/prolog/swipl-result.n3 --pass > swipl-result-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/prolog/tpl-result.n3 --pass > tpl-result-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/prolog/scryer-prolog-result.n3 --pass > scryer-prolog-result-pass.n3
