#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --tactic limited-answer 5 http://eyereasoner.github.io/eye/reasoning/mi/mi.n3 --query http://eyereasoner.github.io/eye/reasoning/mi/mi-query.n3 --output mi-answer.n3
