#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope --tactic limited-answer 5 http://eyereasoner.github.io/eye/reasoning/mi/mi.n3 --query http://eyereasoner.github.io/eye/reasoning/mi/mi-query.n3 --output mi-answer.n3
