#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --tactic limited-answer 5 http://josd.github.io/eye/reasoning/mi/mi.n3 --query http://josd.github.io/eye/reasoning/mi/mi-query.n3 --output mi-answer.n3
