#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let .. --nope https://eyereasoner.github.io/eye/let/graph/graph.ttl --sparql-forward https://eyereasoner.github.io/eye/let/graph/rpo-rules.rq --sparql-query https://eyereasoner.github.io/eye/let/graph/graph-query.rq --output graph-answer.ttl
