#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/superdense-coding-test/superdense-coding.pl3 --output superdense-coding-output.pl3
