#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/fast-fourier-transform-test/fast-fourier-transform.pl3 --output fast-fourier-transform-output.pl3
