#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --quiet --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/image/year.n3 https://eyereasoner.github.io/eye/color/image/easter.n3 --image ype.pvm
