#!/bin/bash
swipl -x ype.pvm -- --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --query https://eyereasoner.github.io/eye/color/image/query.n3 --output easter-proof.n3
