#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let-sparql .. --nope https://eyereasoner.github.io/eye/let-sparql/control-system/data.ttl --sparql-backward https://eyereasoner.github.io/eye/let-sparql/control-system/rules.rq --sparql-query https://eyereasoner.github.io/eye/let-sparql/control-system/query.rq --output answer.ttl
