#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --no-call-residue-vars --query https://eyereasoner.github.io/eye/reasoning/4number/4number-query.n3 --output 4number-answer.n3
