#!/bin/bash

pushd ~/github.com/josd/eye/reasoning
echo -n > etc.txt
echo "# $(date)" > etc.diff
IMATCH="^diff|^index|^Binary|^--|^\+-|\+\+|^@@|#Processed by|#DONE|in=|#ENDS"

for dir in */
do
    pushd "${dir}"
    ./test --no-genid |& tee -a ../etc.txt
    git diff -U0 . | grep -E -v "$IMATCH" >> ../etc.diff
    popd
done

eye etc.diff --pass > /dev/null
popd
