#!/bin/bash
OK=0
FAILED=0
RED="\033[31m"
PINK="\033[35m"
GREEN="\033[32m"
NORMAL="\033[0;39m"

for dir in */
do
    pushd "${dir}"
    ./test "$@" --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01
    if [[ $(git status -s . | wc -l) -ne 0 ]]; then
        let FAILED++
    else
        let OK++
    fi
    popd
    echo ""
done

echo -e "Tests: ${GREEN}${OK} OK ${RED}${FAILED} FAILED${NORMAL}"
