#!/bin/bash
eye "$@" --nope --pl https://github.com/josd/eye/blob/master/reasoning/fft/fft_program.pl --query https://github.com/josd/eye/blob/master/reasoning/fft/fft_query.n3 > fft_answer.n3
eye "$@" --pl https://github.com/josd/eye/blob/master/reasoning/fft/fft_program.pl --query https://github.com/josd/eye/blob/master/reasoning/fft/fft_query.n3 > fft_proof.n3
