#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/fft/fft.n3 --query http://josd.github.io/eye/reasoning/fft/fft_query.n3 --output fft_answer.n3
