#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --trig https://eyereasoner.github.io/eye/reasoning/ldes/ldes-data.trig --trig https://eyereasoner.github.io/eye/reasoning/ldes/ldes-query.trig --trig-output --output ldes-answer.trig
