#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/quad/example.n4 --pass --output example-pass.n4
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/quad/quad.n4 --pass --output quad-pass.n4
