#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/rif/rifP.n3 --query https://eyereasoner.github.io/eye/color/rif/rifQ.n3 --output rifE.n3
