#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/zebra/zebra.n3 --query http://eyereasoner.github.io/eye/reasoning/zebra/zebraQ.n3 --output zebraE.n3
