#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. https://eyereasoner.github.io/eye/reasoning/zebra/zebra.n3 --query https://eyereasoner.github.io/eye/reasoning/zebra/zebraQ.n3 --output zebraE.n3
