#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/zebra/zebra.n3 --query http://eyereasoner.github.io/eye/reasoning/zebra/zebraQ.n3 --output zebraE.n3
