#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/padovan/padovan.n3 --query http://eyereasoner.github.io/eye/reasoning/padovan/padovanQ.n3 --output padovanA.n3
