#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/padovan/padovan.n3 --query http://josd.github.io/eye/reasoning/padovan/padovanQ.n3 --output padovanA.n3
