#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/padovan/padovan.n3 --query http://eyereasoner.github.io/eye/reasoning/padovan/padovanQ.n3 --output padovanA.n3
