#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/slide33/slide33.n3 --query https://eyereasoner.github.io/eye/reasoning/slide33/slide33-query.n3 --output slide33-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. https://eyereasoner.github.io/eye/reasoning/slide33/slide33.n3 --query https://eyereasoner.github.io/eye/reasoning/slide33/slide33-query.n3 --output slide33-proof.n3
