#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/temp/socrates.n3 --query http://eyereasoner.github.io/eye/reasoning/temp/socrates-query.n3 --output socrates-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/temp/socrates.n3 --query http://eyereasoner.github.io/eye/reasoning/temp/socrates-query.n3 --output socrates-proof.n3
