#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/abc.n3 --output abc-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/abcd.n3 --output abcd-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/complex.n3 --output complex-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/fibonacci.n3 --output fibonacci-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/peano.n3 --output peano-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/rain.n3 --output rain-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/slide28.n3 --output slide28-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/slide32.n3 --output slide32-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/slide33.n3 --output slide33-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/socrates.n3 --output socrates-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --blogic http://josd.github.io/eye/reasoning/blogic/socrates-star.n3 --output socrates-star-answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope --turtle http://josd.github.io/eye/reasoning/bmt/1tt1.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt2.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt3.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt4.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt5.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt6.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt7.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt8.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt9.n3 --turtle http://josd.github.io/eye/reasoning/bmt/1tt10.n3 --blogic http://josd.github.io/eye/reasoning/blogic/bmt.n3 --output bmt-answer.n3
