#!/bin/bash
echo "% Running Lateral tests with Trealla" | tee ./result/result.pl
echo "" | tee -a ./result/result.pl
for f in *.pl
do 
    tpl -g test "$f" | tee -a ./result/result.pl
    echo "" | tee -a ./result/result.pl
done
git diff
