#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/refresh/beetle.n3 --query http://eyereasoner.github.io/eye/reasoning/refresh/beetle-query.n3 --output beetle-answer.n3
