#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/primes/prime.n3 --query http://josd.github.io/eye/reasoning/primes/totientQ.n3 > totientA.n3
