#!/bin/bash
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/image/year.n3 http://eyereasoner.github.io/eye/reasoning/image/easter.n3 --image ype.pvm
