#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning/image . http://josd.github.io/eye/reasoning/image/year.n3 http://josd.github.io/eye/reasoning/image/easter.n3 --image ype.pvm
swipl -x ype.pvm -- "$@" --wcache http://josd.github.io/eye/reasoning/image . --query http://josd.github.io/eye/reasoning/image/query.n3 > easter-proof.n3
