#!/bin/bash
eye "$@" https://github.com/josd/eye/blob/master/reasoning/image/year.n3 https://github.com/josd/eye/blob/master/reasoning/image/easter.n3 --image ype.pvm
swipl -x ype.pvm -- "$@" --query https://github.com/josd/eye/blob/master/reasoning/image/query.n3 > easter-proof.n3
