#!/bin/bash
pushd ~/github.com/eyereasoner/rdfsurfaces-tests > /dev/null
./bin/make_examples.js lib/${1:-eye}.js | tee /dev/stderr | grep Results > ../eye/reasoning/rdfsurfaces/results.txt
popd > /dev/null
