#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/rif/rifP.n3 --query http://eyereasoner.github.io/eye/reasoning/rif/rifQ.n3 --output rifE.n3
