#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let-turtle .. --nope --tactic limited-answer 1 https://eyereasoner.github.io/eye/let-turtle/diamond-property/diamond-property.ttl --output diamond-property-answer.ttl
