#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --query https://eyereasoner.github.io/eye/reasoning/polynomial/polynomial-query.n3 --output polynomial-answer.n3
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --query https://eyereasoner.github.io/eye/reasoning/polynomial/polynomial-query.n3 --output polynomial-proof.n3
