#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/polynomial/polynomial.n3 http://josd.github.io/eye/reasoning/polynomial/polynomials.n3 --query http://josd.github.io/eye/reasoning/polynomial/query.n3 --output result.n3
