#!/bin/bash
eye "$@" http://josd.github.io/eye/reasoning/bmi/bmi_instances.n3 http://josd.github.io/eye/reasoning/bmi/bmi_rules.n3 http://josd.github.io/eye/reasoning/bmi/weightStatus_rules.n3 http://josd.github.io/eye/reasoning/bmi/age_rules_backward.n3 --query http://josd.github.io/eye/reasoning/bmi/bmi_query.n3 > bmi_proof.n3
