#!/bin/bash

for file in *.trig
do
    echo $file
    riot --out trig $file | eye --quiet --nope - --output answer/$file 2> /dev/null
    riot --out trig $file | eye --quiet - --output proof/$file 2> /dev/null
done
git diff
git reset --hard HEAD
echo ""

echo allcases.trig
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --nope * --output answer/allcases.trig 2> /dev/null
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 * --output proof/allcases.trig 2> /dev/null
git diff
