#!/bin/bash

for file in *.trig
do
    echo $file
    riot --out trig $file | eye --quiet --nope - --output answer/$file 2> /dev/null
    riot --out trig $file | eye --quiet - --output proof/$file 2> /dev/null
done
git diff
git reset --hard HEAD
echo ""

echo allcases.trig
eye --quiet --nope * --output answer/allcases.trig 2> /dev/null
eye --quiet * --output proof/allcases.trig 2> /dev/null
git diff
