#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
FAILED=0

echo -e "${YELLOW}-------------------${NORMAL}"
echo -e "${YELLOW}Running lingua/test${NORMAL}"
echo -e "${YELLOW}-------------------${NORMAL}"
echo ""

for file in *.trig
do
    echo -en "${file} "
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye .. --nope https://eyereasoner.github.io/eye/lingua/$file --output answer/$file
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye .. https://eyereasoner.github.io/eye/lingua/$file --output proof/$file
    if [[ $(git diff */$file | wc -l) -eq 0 ]]; then
        echo -e "${GREEN}OK${NORMAL}"
        ((OK++))
    else
        echo -e "${RED}FAILED${NORMAL}"
        ((FAILED++))
    fi
done

echo ""
echo -e "${YELLOW}Tests:${NORMAL} ${GREEN}${OK} OK${NORMAL} ${RED}${FAILED} FAILED${NORMAL}"

if [[ ${FAILED} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
