#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/fibonacci/fibonacci.n3 --query http://josd.github.io/eye/reasoning/fibonacci/fibonacciQ.n3 --output fibonacciA.n3
