#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/fibonacci/fibonacci.n3 --query http://eyereasoner.github.io/eye/reasoning/fibonacci/fibonacciQ.n3 --output fibonacciA.n3
