#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/nbbn/nbbn-plugin.n3 http://eyereasoner.github.io/eye/reasoning/nbbn/nbbn-model.n3 --query http://eyereasoner.github.io/eye/reasoning/nbbn/nbbn-query.n3 --output nbbn_proof.n3
