#!/bin/bash
eye "$@" --n3 https://github.com/josd/eye/blob/master/reasoning/nbbn/nbbn-plugin.n3 --n3 https://github.com/josd/eye/blob/master/reasoning/nbbn/nbbn-model.n3 --query https://github.com/josd/eye/blob/master/reasoning/nbbn/nbbn-query.n3 > nbbn_proof.n3
