#!/bin/bash

function test {
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/bell.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/easter.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/einstein.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/euler.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/fibonacci.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/graph.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/grapht.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/grover.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/list.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/socrates.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/tree.n3
    python3 eye.py "$@" http://josd.github.io/eye/looking/swap/xanthippe.n3
    python3 eye.py "$@" http://www.agfa.com/w3c/euler/example003P.n3
    python3 eye.py "$@" http://www.agfa.com/w3c/euler/medI.n3
}

test |& tee test.txt
test --why |& tee -a test.txt
