#!/bin/bash
echo -n "" | tee result.n3
for f in *.pl
do
    if [ "$f" != "heisenberg.pl" ]
    then
        echo "# running $f" | tee -a result.n3
        tpl -g run,halt heisenberg.pl "$f" | tee -a result.n3
        echo "" | tee -a result.n3
    fi
done
