#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/heisenberg/swipl-result.n3 --pass > swipl-result-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/heisenberg/tpl-result.n3 --pass > tpl-result-pass.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/heisenberg/scryer-prolog-result.n3 --pass > scryer-prolog-result-pass.n3
