#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/3outof5/sample.n3 --query http://eyereasoner.github.io/eye/reasoning/3outof5/query.n3 --output answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/3outof5/sample.n3 --query http://eyereasoner.github.io/eye/reasoning/3outof5/query.n3 --output proof.n3
