#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/3outof5/sample.n3 --query http://josd.github.io/eye/reasoning/3outof5/query.n3 --output answer.n3
