#!/bin/bash
eye "$@" --nope --wcache https://github.com/josd/eye/blob/master/reasoning/4eq . --pl https://github.com/josd/eye/blob/master/reasoning/4eq/4eq_program.pl --query https://github.com/josd/eye/blob/master/reasoning/4eq/4eq_query.n3 > 4eq_answer.n3
eye "$@" --wcache https://github.com/josd/eye/blob/master/reasoning/4eq . --pl https://github.com/josd/eye/blob/master/reasoning/4eq/4eq_program.pl --query https://github.com/josd/eye/blob/master/reasoning/4eq/4eq_query.n3 > 4eq_proof.n3
