#!/bin/bash
eye "$@" --nope --wcache http://josd.github.io/eye/reasoning/4eq . --prolog http://josd.github.io/eye/reasoning/4eq/4eq_program.pl --query http://josd.github.io/eye/reasoning/4eq/4eq_query.n3 > 4eq_answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning/4eq . --prolog http://josd.github.io/eye/reasoning/4eq/4eq_program.pl --query http://josd.github.io/eye/reasoning/4eq/4eq_query.n3 > 4eq_proof.n3
