#!/bin/bash
eye "$@" --nope --wcache https://raw.githubusercontent.com/josd/eye/master/reasoning/4eq . --pl https://raw.githubusercontent.com/josd/eye/master/reasoning/4eq/4eq_program.pl --query https://raw.githubusercontent.com/josd/eye/master/reasoning/4eq/4eq_query.n3 > 4eq_answer.n3
eye "$@" --wcache https://raw.githubusercontent.com/josd/eye/master/reasoning/4eq . --pl https://raw.githubusercontent.com/josd/eye/master/reasoning/4eq/4eq_program.pl --query https://raw.githubusercontent.com/josd/eye/master/reasoning/4eq/4eq_query.n3 > 4eq_proof.n3
