#!/bin/sh

# set -e

TMP=tmp.out
PROLOG=${1:-"tpl -q --ns"}

trap "rm -f $TMP" EXIT

failed_count=0
succeeded_count=0

echo "Using $PROLOG" | tee test.txt

for source in ./*

do
    case "$source" in
        *.pl)
            cmd=$PROLOG
            ;;
        *)
            continue
    esac

    echo "Running $source ..." | tee -a test.txt
    $cmd "$source" > $TMP
    echo -n true | diff -a - $TMP | tee -a test.txt
    if [ $? -eq 0 ]
    then
        succeeded_count=$(expr $succeeded_count + 1)
    else
        failed_count=$(expr $failed_count + 1)
    fi
done

cat <<EOF | tee -a test.txt

============
TEST SUMMARY
============
Failed: $failed_count
Succeeded: $succeeded_count
EOF
