#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/medic/medic.n3 --query http://eyereasoner.github.io/eye/reasoning/medic/medicF.n3 --output medicE.n3
