#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. https://eyereasoner.github.io/eye/reasoning/medic/medic.n3 --query https://eyereasoner.github.io/eye/reasoning/medic/medicF.n3 --output medicE.n3
