#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/ttl-to-rdfa/ttl-to-rdfa.n3 http://eyereasoner.github.io/eye/reasoning/ttl-to-rdfa/health_schema_org.ttl --strings --output health_schema_org.html
