#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/ttl-to-rdfa/ttl-to-rdfa.n3 https://eyereasoner.github.io/eye/reasoning/ttl-to-rdfa/health_schema_org.ttl --strings --output health_schema_org.html
