#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/ttl-to-rdfa/ttl-to-rdfa.n3 http://josd.github.io/eye/reasoning/ttl-to-rdfa/health_schema_org.ttl --strings --output health_schema_org.html
