#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/deep-taxonomy-test/deep-taxonomy.pl3 --output deep-taxonomy-output.pl3
