#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/utf8/utf8.n3 --pass --output utf8_proof.n3
