#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/pi/pi.n3 --query http://eyereasoner.github.io/eye/reasoning/pi/pi-query.n3 --output pi-proof.n3
