#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/pi/pi.n3 --query http://eyereasoner.github.io/eye/reasoning/pi/pi-query.n3 --output pi-proof.n3
