#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/peano/peano.n3 --query https://eyereasoner.github.io/eye/reasoning/peano/peano-query.n3 --output peano-answer.n3
