#!/bin/bash
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/dialogical-reasoning/test-dr-ws-result.n3 --pass --output test-dr-ws-result-pass.n3
