#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/entail/socrates.n3 --entail https://eyereasoner.github.io/eye/color/entail/socrates-claim.n3 --output socrates-check.n3
