#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/prime/prime.n3 --query http://josd.github.io/eye/reasoning/prime/prime_query.n3 --output prime_answer.n3
