#!/bin/bash
eye "$@" --nope --pl http://josd.github.io/eye/reasoning/queens/queens_program.pl --query http://josd.github.io/eye/reasoning/queens/queens_query.n3 > queens_answer.n3
eye "$@" --pl http://josd.github.io/eye/reasoning/queens/queens_program.pl --query http://josd.github.io/eye/reasoning/queens/queens_query.n3 > queens_proof.n3
