#!/bin/bash
eye "$@" --nope --plugin http://josd.github.io/eye/reasoning/queens/queens_program.eyepl --query http://josd.github.io/eye/reasoning/queens/queens_query.n3 > queens_answer.n3
eye "$@" --plugin http://josd.github.io/eye/reasoning/queens/queens_program.eyepl --query http://josd.github.io/eye/reasoning/queens/queens_query.n3 > queens_proof.n3
