#!/bin/bash
eye "$@" --nope --pl https://raw.githubusercontent.com/josd/eye/master/reasoning/queens/queens_program.pl --query https://raw.githubusercontent.com/josd/eye/master/reasoning/queens/queens_query.n3 > queens_answer.n3
eye "$@" --pl https://raw.githubusercontent.com/josd/eye/master/reasoning/queens/queens_program.pl --query https://raw.githubusercontent.com/josd/eye/master/reasoning/queens/queens_query.n3 > queens_proof.n3
