#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/entail/socrates.n3 --entail http://josd.github.io/eye/reasoning/entail/socrates-claim.n3 --output socrates-check.n3
