#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/entail/socrates.n3 --entail http://eyereasoner.github.io/eye/reasoning/entail/socrates-claim.n3 --output socrates-check.n3
