#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/n3patch/sample-data.ttl https://eyereasoner.github.io/eye/color/n3patch/patch-rule.n3 --pass --output patched-data.ttl
