#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --trig-output https://eyereasoner.github.io/eye/reasoning/n3trig/in.n3 --pass-all --output out.trig
