#!/bin/bash
eye "$@" --nope --tactic limited-answer 2 --turtle http://josd.github.io/eye/reasoning/4color/4color_data.ttl http://josd.github.io/eye/reasoning/4color/4color_rules.n3 --query http://josd.github.io/eye/reasoning/4color/4color_query.n3 > 4color_answer.n3
eye "$@" --tactic limited-answer 2 --turtle http://josd.github.io/eye/reasoning/4color/4color_data.ttl http://josd.github.io/eye/reasoning/4color/4color_rules.n3 --query http://josd.github.io/eye/reasoning/4color/4color_query.n3 > 4color_proof.n3
