#!/bin/bash
eye "$@" --nope --turtle http://josd.github.io/eye/reasoning/4color/4color_data.ttl --n3 http://josd.github.io/eye/reasoning/4color/4color_rules.n3 --query http://josd.github.io/eye/reasoning/4color/4color_query.n3 > 4color_answer.n3
