#!/bin/bash
eye "$@" --nope --tactic limited-answer 2 --turtle https://github.com/josd/eye/blob/master/reasoning/4color/4color_data.n3 https://github.com/josd/eye/blob/master/reasoning/4color/4color_rules.n3 --query https://github.com/josd/eye/blob/master/reasoning/4color/4color_query.n3 > 4color_answer.n3
eye "$@" --tactic limited-answer 2 --turtle https://github.com/josd/eye/blob/master/reasoning/4color/4color_data.n3 https://github.com/josd/eye/blob/master/reasoning/4color/4color_rules.n3 --query https://github.com/josd/eye/blob/master/reasoning/4color/4color_query.n3 > 4color_proof.n3
