#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let-sparql .. --nope https://eyereasoner.github.io/eye/let-sparql/proof-by-contradiction/example1.rq --sparql-query https://eyereasoner.github.io/eye/let-sparql/proof-by-contradiction/example1-query.rq --output example1-answer.ttl

eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/let-sparql .. --nope https://eyereasoner.github.io/eye/let-sparql/proof-by-contradiction/example2.rq --sparql-query https://eyereasoner.github.io/eye/let-sparql/proof-by-contradiction/example2-query.rq --output example2-answer.ttl
