# Generated by codec.py
# Edit DOC and run this file to print N3 to stdout.

DOC = {'prefixes': {'': 'http://example.org/#'},
 'rules': [{'direction': 'forward',
            'if': ['?x a :City', '?x :inCountry :Belgium'],
            'then': ['?x a :HumanCommunity']},
           {'direction': 'backward',
            'if': ['?x a :City', '?x a :UrbanArea', '?x :inCountry :Belgium'],
            'then': ['?x a :HumanCommunity']},
           {'direction': 'query',
            'if': ['?x a :City', '?x :inCountry :Belgium'],
            'then': ['?x :answer "Yes"']}],
 'triples': [':Ghent a :City',
             ':Ghent :inCountry :Belgium',
             ':Ghent :hasName "Ghent"',
             ':Ghent :hasName "Gent"',
             '_:b1 a :Port',
             '_:b1 :name "Antwerp Port"',
             ':Antwerp :hasPart _:b1']}

def _doc_to_n3(doc):
    def _trip(s):
        s = s.strip()
        return s if s.endswith('.') else s + ' .'
    lines = []
    for pfx, iri in doc.get('prefixes', {}).items():
        lines.append('@prefix ' + (pfx+':' if pfx else ':') + ' <' + iri + '> .')
    if lines:
        lines.append('')
    for t in doc.get('triples', []):
        lines.append(_trip(t))
    if doc.get('triples'):
        lines.append('')
    for r in doc.get('rules', []):
        if_part = ' . '.join(s.rstrip('.') for s in r.get('if', []))
        then_part = ' . '.join(s.rstrip('.') for s in r.get('then', []))
        d = r.get('direction', 'forward')
        if d == 'backward':
            op, left, right = '<=', then_part, if_part
        elif d == 'query':
            op, left, right = '=^', if_part, then_part
        else:
            op, left, right = '=>', if_part, then_part
        if left and not left.endswith('.'):
            left += ' .'
        if right and not right.endswith('.'):
            right += ' .'
        lines.append('{ ' + left + ' } ' + op + ' { ' + right + ' } .')
    return '\n'.join(lines).strip() + '\n'

if __name__ == '__main__':
    print(_doc_to_n3(DOC), end='')
