#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/rdf-star-reasoning/test.n3 --pass > answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/rdf-star-reasoning/socrates.n3 --pass > socrates-pass.n3
