#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/rdf-star-reasoning/test.n3 --pass --output answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/rdf-star-reasoning/socrates.n3 --pass --output socrates-pass.n3
