#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --trig https://eyereasoner.github.io/eye/reasoning/bng/socrates.trig https://eyereasoner.github.io/eye/reasoning/bng/bng.n3 --output socrates-answer.ttl
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --trig https://eyereasoner.github.io/eye/reasoning/bng/age.trig https://eyereasoner.github.io/eye/reasoning/bng/bng.n3 --output age-answer.ttl
