#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/perfect-number-test/perfect-number.pl3 --output perfect-number-output.pl3
