#!/bin/bash
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/qg/qg.n3 http://eyereasoner.github.io/eye/reasoning/rpo/owl-sameAs-ext.n3 --pass --output qg-answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/qg/nqg.n3 http://eyereasoner.github.io/eye/reasoning/rpo/owl-sameAs-ext.n3 --pass --output nqg-answer.n3
