#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --prolog https://eyereasoner.github.io/eye/reasoning/traveling-salesman/traveling-salesman.pl --output traveling-salesman-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --prolog https://eyereasoner.github.io/eye/reasoning/traveling-salesman/traveling-salesman.pl --output traveling-salesman-proof.n3
