#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/dining-philosophers-test/dining-philosophers.pl3 --output dining-philosophers-output.pl3
