#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/snaf/demo.n3 http://eyereasoner.github.io/eye/reasoning/snaf/rules.n3 --pass --output answer.n3
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/snaf/demo.n3 http://eyereasoner.github.io/eye/reasoning/snaf/rules.n3 --pass --output proof.n3
