#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/snaf/demo.n3 http://josd.github.io/eye/reasoning/snaf/rules.n3 --pass --output answer.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/snaf/demo.n3 http://josd.github.io/eye/reasoning/snaf/rules.n3 --pass --output proof.n3
