#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/arcus .. --nope https://eyereasoner.github.io/eye/arcus/combinatorics/combination.ttl --output combination-answer.ttl

eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/arcus .. --nope https://eyereasoner.github.io/eye/arcus/combinatorics/permutation.ttl --output permutation-answer.ttl
