#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/proof-by-cases-test/proof-by-cases.pl3 --output proof-by-cases-output.pl3
