#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example1.n3 --pass-all > example1-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example2.n3 --pass-all > example2-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example3.n3 --pass-all > example3-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example4.n3 --pass-all > example4-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example5.n3 --pass-all > example5-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example6.n3 --pass-all > example6-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example7.n3 --pass-all > example7-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example8.n3 --pass-all > example8-pass-all.n3
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/bnodes/example9.n3 --pass-all > example9-pass-all.n3
