PREFIX : <http://example.org/#>

CONSTRUCT {
    (1 0 1 0 0 1) :compute ?A1.
    (1 0 1 1 1 1) :compute ?A2.
    (1 1 1 1 1 1) :compute ?A3.
    () :compute ?A4.
} WHERE {
    (1 0 1 0 0 1) :compute ?A1.
    (1 0 1 1 1 1) :compute ?A2.
    (1 1 1 1 1 1) :compute ?A3.
    () :compute ?A4.
}
