#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/turing/turing.n3 --query http://eyereasoner.github.io/eye/reasoning/turing/turingQ.n3 --output turing_proof.n3
