#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/turing/turing.n3 --query http://josd.github.io/eye/reasoning/turing/turingQ.n3 --output turing_proof.n3
