#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/einstein/einstein.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/einstein/einsteinQ.n3 > einsteinE.n3
