#!/bin/bash
echo "% Test results for EYE Linked Data" | tee ./result/result.pl
echo "" | tee -a ./result/result.pl
for f in *.pl
do 
    tpl --ffai -g test "$f" | tee -a ./result/result.pl
    echo "" | tee -a ./result/result.pl
done
git diff
