PREFIX pack: <https://example.org/ns/package#>
PREFIX graph: <http://www.w3.org/2000/10/swap/graph#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>

CONSTRUCT {
    ?N pack:content ?C.
} WHERE {
    ?S pack:package ?O.
    ?O graph:statement ?G.
    ?G log:includes {
        ?N pack:content ?C.
    }
}
