#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/basic-monadic-test/basic-monadic.pl3 --output basic-monadic-output.pl3
