#!/bin/bash
for file in *.trig
do
    eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --trig https://eyereasoner.github.io/eye/reasoning/gsm/$file https://eyereasoner.github.io/eye/reasoning/gsm/gsm.n3 --trig-output --output output/$file
done
