#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. http://eyereasoner.github.io/eye/reasoning/gedcom/gedcom-facts.n3 http://eyereasoner.github.io/eye/reasoning/gedcom/gedcom-relations.n3 http://eyereasoner.github.io/eye/reasoning/gedcom/rpo-rules.n3 --query http://eyereasoner.github.io/eye/reasoning/gedcom/gedcom-filter.n3 --output gedcom-proof.n3
