#!/bin/bash
eye "$@" https://raw.githubusercontent.com/josd/eye/master/reasoning/gedcom/gedcom-facts.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/gedcom/gedcom-relations.n3 https://raw.githubusercontent.com/josd/eye/master/reasoning/gedcom/rpo-rules.n3 --query https://raw.githubusercontent.com/josd/eye/master/reasoning/gedcom/gedcom-filter.n3 > gedcom-proof.n3
