#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. http://josd.github.io/eye/reasoning/gedcom/gedcom-facts.n3 http://josd.github.io/eye/reasoning/gedcom/gedcom-relations.n3 http://josd.github.io/eye/reasoning/gedcom/rpo-rules.n3 --query http://josd.github.io/eye/reasoning/gedcom/gedcom-filter.n3 --output gedcom-proof.n3
