#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/n3patch/sample-data.ttl http://eyereasoner.github.io/eye/reasoning/n3patch/patch-rule.n3 --pass --output patched-data.ttl
