#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/n3patch/sample-data.n3 http://josd.github.io/eye/reasoning/n3patch/patch-rule.n3 --pass --output patched-data.n3
