#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/gps-test/gps-plugin.pl3 --pl3 https://eyereasoner.github.io/eye/reasoning/gps-test/gps-data.pl3 --pl3 https://eyereasoner.github.io/eye/reasoning/gps-test/gps-query.pl3 --output gps-output.pl3
