#!/bin/bash -x
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache http://eyereasoner.github.io/eye/reasoning .. --hmac-key k123 http://eyereasoner.github.io/eye/reasoning/crypto/cryptoP.n3 --pass --output crypto-proof.n3
