#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/equations/equation.n3 --query http://josd.github.io/eye/reasoning/equations/equationQ.n3 > equationA.n3
