#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope https://eyereasoner.github.io/eye/reasoning/socrates/socrates.ttl https://eyereasoner.github.io/eye/reasoning/socrates/socrates.rq --query https://eyereasoner.github.io/eye/reasoning/socrates/socrates-query.rq --output socrates-answer.ttl
