#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. --nope https://eyereasoner.github.io/eye/color/filter/filter.n3 --query https://eyereasoner.github.io/eye/color/filter/filter-query.n3 --output filter-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/filter/filter.n3 --query https://eyereasoner.github.io/eye/color/filter/filter-query.n3 --output filter-proof.n3
