#!/bin/bash
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/beetle/beetle.n3 http://eyereasoner.github.io/eye/reasoning/beetle/rpf.n3 --pass-only-new --output beetle-answer.n3
