#!/bin/bash -x
eye "$@" --wcache http://eyereasoner.github.io/eye/reasoning .. --nope http://eyereasoner.github.io/eye/reasoning/beetle/beetle.n3 http://eyereasoner.github.io/eye/reasoning/beetle/raf.n3 --query http://eyereasoner.github.io/eye/reasoning/beetle/beetle-query.n3 --output beetle-answer.n3
