#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --pl3 https://eyereasoner.github.io/eye/reasoning/proof-by-induction-test/proof-by-induction.pl3 --output proof-by-induction-output.pl3
