PREFIX : <https://eyereasoner.github.io/ns#>

CONSTRUCT {
    (0 0) :ackermann ?A0.
    (0 6) :ackermann ?A1.
    (1 2) :ackermann ?A2.
    (1 7) :ackermann ?A3.
    (2 2) :ackermann ?A4.
    (2 9) :ackermann ?A5.
    (3 4) :ackermann ?A6.
    (3 14) :ackermann ?A7.
    (4 0) :ackermann ?A8.
    (4 1) :ackermann ?A9.
    (4 2) :ackermann ?A10.
    (5 0) :ackermann ?A11.
} WHERE {
    (0 0) :ackermann ?A0.
    (0 6) :ackermann ?A1.
    (1 2) :ackermann ?A2.
    (1 7) :ackermann ?A3.
    (2 2) :ackermann ?A4.
    (2 9) :ackermann ?A5.
    (3 4) :ackermann ?A6.
    (3 14) :ackermann ?A7.
    (4 0) :ackermann ?A8.
    (4 1) :ackermann ?A9.
    (4 2) :ackermann ?A10.
    (5 0) :ackermann ?A11.
}
