:- op(1200, xfx, :+).

answer('urn:example:negotiate'('urn:example:agent1',['urn:example:agent2','urn:example:data4'])).

step((request_data(A,B,C):+'urn:example:hasData'(A,D),'urn:example:hasData'(B,E),member(C,E), \+member(C,D),'urn:example:policy'(A,['urn:example:request',C])),('urn:example:hasData'('urn:example:agent1',['urn:example:data1','urn:example:data2','urn:example:data3']),'urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data5','urn:example:data6']),member('urn:example:data4',['urn:example:data4','urn:example:data5','urn:example:data6']), \+member('urn:example:data4',['urn:example:data1','urn:example:data2','urn:example:data3']),'urn:example:policy'('urn:example:agent1',['urn:example:request','urn:example:data4'])),request_data('urn:example:agent1','urn:example:agent2','urn:example:data4')).
step((request_data(A,B,C):+'urn:example:hasData'(A,D),'urn:example:hasData'(B,E),member(C,E), \+member(C,D),'urn:example:policy'(A,['urn:example:request',C])),('urn:example:hasData'('urn:example:agent1',['urn:example:data1','urn:example:data2','urn:example:data3']),'urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data5','urn:example:data6']),member('urn:example:data6',['urn:example:data4','urn:example:data5','urn:example:data6']), \+member('urn:example:data6',['urn:example:data1','urn:example:data2','urn:example:data3']),'urn:example:policy'('urn:example:agent1',['urn:example:request','urn:example:data6'])),request_data('urn:example:agent1','urn:example:agent2','urn:example:data6')).
step((accept_request(A,B,C):+'urn:example:hasData'(A,D),member(C,D),'urn:example:policy'(A,['urn:example:accept',C]),becomes('urn:example:hasData'(B,E),'urn:example:hasData'(B,[C|E]))),('urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data5','urn:example:data6']),member('urn:example:data4',['urn:example:data4','urn:example:data5','urn:example:data6']),'urn:example:policy'('urn:example:agent2',['urn:example:accept','urn:example:data4']),becomes('urn:example:hasData'('urn:example:agent1',['urn:example:data1','urn:example:data2','urn:example:data3']),'urn:example:hasData'('urn:example:agent1',['urn:example:data4','urn:example:data1','urn:example:data2','urn:example:data3']))),accept_request('urn:example:agent2','urn:example:agent1','urn:example:data4')).
step((accept_request(A,B,C):+'urn:example:hasData'(A,D),member(C,D),'urn:example:policy'(A,['urn:example:accept',C]),becomes('urn:example:hasData'(B,E),'urn:example:hasData'(B,[C|E]))),('urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data5','urn:example:data6']),member('urn:example:data4',['urn:example:data4','urn:example:data5','urn:example:data6']),'urn:example:policy'('urn:example:agent2',['urn:example:accept','urn:example:data4']),becomes('urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data5','urn:example:data6']),'urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data4','urn:example:data5','urn:example:data6']))),accept_request('urn:example:agent2','urn:example:agent2','urn:example:data4')).
step((accept_request(A,B,C):+'urn:example:hasData'(A,D),member(C,D),'urn:example:policy'(A,['urn:example:accept',C]),becomes('urn:example:hasData'(B,E),'urn:example:hasData'(B,[C|E]))),('urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data5','urn:example:data6']),member('urn:example:data6',['urn:example:data4','urn:example:data5','urn:example:data6']),'urn:example:policy'('urn:example:agent2',['urn:example:accept','urn:example:data6']),becomes('urn:example:hasData'('urn:example:agent1',['urn:example:data4','urn:example:data1','urn:example:data2','urn:example:data3']),'urn:example:hasData'('urn:example:agent1',['urn:example:data6','urn:example:data4','urn:example:data1','urn:example:data2','urn:example:data3']))),accept_request('urn:example:agent2','urn:example:agent1','urn:example:data6')).
step((accept_request(A,B,C):+'urn:example:hasData'(A,D),member(C,D),'urn:example:policy'(A,['urn:example:accept',C]),becomes('urn:example:hasData'(B,E),'urn:example:hasData'(B,[C|E]))),('urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data5','urn:example:data6']),member('urn:example:data6',['urn:example:data4','urn:example:data5','urn:example:data6']),'urn:example:policy'('urn:example:agent2',['urn:example:accept','urn:example:data6']),becomes('urn:example:hasData'('urn:example:agent2',['urn:example:data4','urn:example:data4','urn:example:data5','urn:example:data6']),'urn:example:hasData'('urn:example:agent2',['urn:example:data6','urn:example:data4','urn:example:data4','urn:example:data5','urn:example:data6']))),accept_request('urn:example:agent2','urn:example:agent2','urn:example:data6')).
step((reject_request(A,B,C):+'urn:example:hasData'(A,D),(\+member(C,D); \+'urn:example:policy'(A,['urn:example:accept',C]))),('urn:example:hasData'('urn:example:agent1',['urn:example:data6','urn:example:data4','urn:example:data1','urn:example:data2','urn:example:data3']),(\+member(sk_1,['urn:example:data6','urn:example:data4','urn:example:data1','urn:example:data2','urn:example:data3']); \+'urn:example:policy'('urn:example:agent1',['urn:example:accept',sk_1]))),reject_request('urn:example:agent1',sk_0,sk_1)).
step((reject_request(A,B,C):+'urn:example:hasData'(A,D),(\+member(C,D); \+'urn:example:policy'(A,['urn:example:accept',C]))),('urn:example:hasData'('urn:example:agent2',['urn:example:data6','urn:example:data4','urn:example:data4','urn:example:data5','urn:example:data6']),(\+member(sk_1,['urn:example:data6','urn:example:data4','urn:example:data4','urn:example:data5','urn:example:data6']); \+'urn:example:policy'('urn:example:agent2',['urn:example:accept',sk_1]))),reject_request('urn:example:agent2',sk_0,sk_1)).
step(('urn:example:negotiate'(A,[B,C]):+request_data(A,B,C),(accept_request(B,A,C);reject_request(B,A,C))),(request_data('urn:example:agent1','urn:example:agent2','urn:example:data4'),(accept_request('urn:example:agent2','urn:example:agent1','urn:example:data4');reject_request('urn:example:agent2','urn:example:agent1','urn:example:data4'))),'urn:example:negotiate'('urn:example:agent1',['urn:example:agent2','urn:example:data4'])).
step(('urn:example:negotiate'(A,[B,C]):+request_data(A,B,C),(accept_request(B,A,C);reject_request(B,A,C))),(request_data('urn:example:agent1','urn:example:agent2','urn:example:data6'),(accept_request('urn:example:agent2','urn:example:agent1','urn:example:data6');reject_request('urn:example:agent2','urn:example:agent1','urn:example:data6'))),'urn:example:negotiate'('urn:example:agent1',['urn:example:agent2','urn:example:data6'])).
step((true:+'urn:example:negotiate'('urn:example:agent1',['urn:example:agent2','urn:example:data4'])),'urn:example:negotiate'('urn:example:agent1',['urn:example:agent2','urn:example:data4']),true).
