#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/polynomials/polynomial.n3 --query http://josd.github.io/eye/reasoning/polynomials/query.n3 > result.n3
