#!/bin/bash
eye "$@" --turtle https://github.com/josd/eye/blob/master/reasoning/djiti/graph-10.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-10.n3
eye "$@" --turtle https://github.com/josd/eye/blob/master/reasoning/djiti/graph-100.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-100.n3
eye "$@" --turtle https://github.com/josd/eye/blob/master/reasoning/djiti/graph-1000.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-1000.n3
eye "$@" --turtle https://github.com/josd/eye/blob/master/reasoning/djiti/graph-10000.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-10000.n3
eye "$@" --proof https://github.com/josd/eye/blob/master/reasoning/djiti/proof-10.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-2-10.n3
eye "$@" --proof https://github.com/josd/eye/blob/master/reasoning/djiti/proof-100.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-2-100.n3
eye "$@" --proof https://github.com/josd/eye/blob/master/reasoning/djiti/proof-1000.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-2-1000.n3
eye "$@" --proof https://github.com/josd/eye/blob/master/reasoning/djiti/proof-10000.n3 --query https://github.com/josd/eye/blob/master/reasoning/djiti/query.n3 > proof-2-10000.n3
