#!/bin/bash
eye "$@" --turtle http://josd.github.io/eye/reasoning/djiti/graph-10.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-10.n3
eye "$@" --turtle http://josd.github.io/eye/reasoning/djiti/graph-100.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-100.n3
eye "$@" --turtle http://josd.github.io/eye/reasoning/djiti/graph-1000.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-1000.n3
eye "$@" --turtle http://josd.github.io/eye/reasoning/djiti/graph-10000.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-10000.n3
eye "$@" --twinkle http://josd.github.io/eye/reasoning/djiti/proof-10.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-2-10.n3
eye "$@" --twinkle http://josd.github.io/eye/reasoning/djiti/proof-100.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-2-100.n3
eye "$@" --twinkle http://josd.github.io/eye/reasoning/djiti/proof-1000.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-2-1000.n3
eye "$@" --twinkle http://josd.github.io/eye/reasoning/djiti/proof-10000.n3 --query http://josd.github.io/eye/reasoning/djiti/query.n3 > proof-2-10000.n3
