#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --query https://eyereasoner.github.io/eye/reasoning/evolutionary-algorithm/evolutionary-algorithm-query.n3 --output evolutionary-algorithm-answer.n3
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/reasoning .. --query https://eyereasoner.github.io/eye/reasoning/evolutionary-algorithm/evolutionary-algorithm-query.n3 --output evolutionary-algorithm-proof.n3
