#!/bin/bash
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --nope --query https://eyereasoner.github.io/eye/reasoning/evolutionary-algorithm/evolutionary-algorithm-query.n3 --output evolutionary-algorithm-answer.n3
eye --quiet --wcache https://eyereasoner.github.io/eye/reasoning .. --query https://eyereasoner.github.io/eye/reasoning/evolutionary-algorithm/evolutionary-algorithm-query.n3 --output evolutionary-algorithm-proof.n3
