#!/bin/bash
eye "$@"  http://josd.github.io/eye/reasoning/fgcm/fgcm-plugin.n3  http://josd.github.io/eye/reasoning/fcm/fl-rules.n3  http://josd.github.io/eye/reasoning/fgcm/patient.n3  http://josd.github.io/eye/reasoning/fgcm/fgcm-model.n3 --query http://josd.github.io/eye/reasoning/fgcm/fgcm-query.n3 > fgcm_proof.n3
