#!/bin/bash
eye "$@" --wcache http://josd.github.io/eye/reasoning .. --nope http://josd.github.io/eye/reasoning/equation/equation.n3 --query http://josd.github.io/eye/reasoning/equation/equationQ.n3 --output equationA.n3
