#!/bin/bash
eye --quiet --skolem-genid 8b98b360-9a70-4845-b52c-c675af60ad01 --wcache https://eyereasoner.github.io/eye/color .. https://eyereasoner.github.io/eye/color/h2o/hypothesis-001.n3 https://eyereasoner.github.io/eye/color/h2o/data-001.n3 https://eyereasoner.github.io/eye/color/h2o/rules-001.n3 --query https://eyereasoner.github.io/eye/color/h2o/query-001.n3 --output proof-001.n3
