#!/bin/bash

# ---------------
# Scripting tests
# ---------------

pushd ~/github.com/josd/eye/scripting
echo "# $(date)" > scripting.txt
echo "# $(date)" > scripting.diff
IMATCH="^diff|^index|^Binary|^--|^\+-|\+\+|^@@"

pushd 4color; ./test "$@" 2>&1 | tee -a ../scripting.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../scripting.diff; popd
pushd bell; ./test "$@" 2>&1 | tee -a ../scripting.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../scripting.diff; popd
pushd easter; ./test "$@" 2>&1 | tee -a ../scripting.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../scripting.diff; popd
pushd euler; ./test "$@" 2>&1 | tee -a ../scripting.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../scripting.diff; popd
pushd fibonacci; ./test "$@" 2>&1 | tee -a ../scripting.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../scripting.diff; popd
pushd grover; ./test "$@" 2>&1 | tee -a ../scripting.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../scripting.diff; popd
pushd queens; ./test "$@" 2>&1 | tee -a ../scripting.txt; git diff -U0 . | grep -E -v "$IMATCH" >> ../scripting.diff; popd

cat scripting.diff
popd
