#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
FAILED=0

echo -e "${YELLOW}Running eye/rdfreasoning/test${NORMAL}"
echo ""

for dir in */
do
    pushd "${dir}" > /dev/null
    ./test
    if [[ $(git diff . | wc -l) -ne 0 ]]; then
        echo -e "${RED}${dir} FAILED${NORMAL}"
        ((FAILED++))
    else
        echo -e "${GREEN}${dir} OK${NORMAL}"
        ((OK++))
    fi
    popd  > /dev/null
    echo ""
done

echo -e "Tests: ${GREEN}${OK} OK${NORMAL} ${RED}${FAILED} FAILED${NORMAL}"

if [[ ${FAILED} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
