PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX : <http://example.org/#>

# \Every x: type(x, Resource)
CONSTRUCT {
    ?x a rdfs:Resource.
} WHERE {}

# Everybody loves somebody who is lonely
CONSTRUCT {
    ?A :loves ?B.
} WHERE {
    (?A) log:skolem ?B.
}

CONSTRUCT {
    ?B :is :lonely.
} WHERE {
    (?A) log:skolem ?B.
}
