#!/bin/bash
eye "$@" --nope --blogic --n3p-output --n3p contradiction.s | tee contradiction-answer.s
eye "$@" --nope --blogic --n3p-output --n3p contradiction5.s | tee contradiction5-answer.s
eye "$@" --nope --blogic --n3p-output --n3p contradiction-builtin.s | tee contradiction-builtin-answer.s
